### ISSUE TITLE
What should the default tolerance (or "success feedback" window) be?

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#14]
Aggregation of discussion from the Design doc and Issue #7 

> What is the window “success feedback” (aka tolerance)?
(4/10/2020) Visually, MK has implemented a “tolerance” parameter that is linked (multiplicatively) to the value of the lower bar.
This means that at low height, the tolerance is small and larger at large heights.
Next: It may be better to tie the tolerance to the proportion a/b instead or create a piecewise tolerance for extreme values.

Emily's thoughts:
>Brett, Dor, Michael - what’s the factor that will determine our decision on this? Is it a usability issue, so the tolerance value will be determined by what allows users to have reasonable success in keeping continuous feedback as they move the objects up/down continuously, or are there more pedagogically focused needs to attend to first? If it’s something we can sort out quickly, we should do so, and get the tolerance slider out of the interface. If it’s something we’ll need time to sort out, we should brainstorm other strategies for supporting on-the-fly changes. We can’t user test well (or have folks brainstorm about the visual design) with that big ol’ tolerance slider where it is now. 

Dor's Response:
>This will be difficult for me to determine remotely. I do not believe there is an ideal solution, only an optimization. I would be glad with any solution that deploys a tolerance of: (a) uniform distance across ratio items; except when (b) the solution brings the fingers very near each other, in which case the tolerance should be weighted down, so that the feedback is clear.

& Dor from #7 
>My hunch would be to try out various versions, making sure we strike a balance between, on the on hand, having some minimal differentiation at the low values near the bottom of the screen where it’s crowded and, on the other hand, having a more-or-less uniform margin higher up. Of course, arguable, if the ratio is 9:10…, then even higher up on the screen we cannot have large margins (bc/ then 10:10 might be greenish). So perhaps the algorithm should be linked to the a/b relation.

@zepumph 's thoughts on multi-platform support:
>In regards to multi-device support:
The "layout bounds" is what we call the space in the sim in which you can drag the objects around. This rectangle is defined generally, and is often consistent across sims. It scales based on the device screen dimensions and will always have the same aspect ratio. From this note that we can create values for tolerance etc in the model that will behave very similarly across devices since they will all behave in a way that is constrained within the layout bounds of the sim.

**Comment by zepumph** [comment]
You summed things up very well! I will add that since last speaking, I have updated the model to be a bit more clear in these terms. Now 0 is the bottom, and 1 is the top. Thus .05 (the tolerance) is actually 1/20 of the height. This change occurred just today as part of #23. Hopefully that can yield a more quantitatively designed tolerance, and it should also make it easier if you want it to be a function of the height or other parameters. Unassigning until needed.

**Comment by emily-phet** [comment]
Great! With the grid in place now, we'll be able to get more specific feedback on the tolerance across devices and settings. Let's see what comes from the team this week.

**Comment by zepumph** [comment]
In the above commit, I made `?tolerance=.05` a query parameter, with that as the default. It felt good to mess around with values even up to .2, just to get an idea of what is "too far." Let me know if I can help this design any other ways.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/ratio-and-proportion/issues/45#issuecomment-629849794 @emily-phet asked the default tolerance to be a bit easier. I'm going to make it .1 for now.

**Comment by zepumph** [comment]
Today during sound meeting, it was brought up again that we will likely want to change the tolerance algorithm so that +- distance from ratio doesn't differ so drastically when the ratio is small vs large.  Right now the fitness is a function of how different the two ratio half values are, but we could just as easily make it a flat distance from the ratio, that is independent of the left/right values. 

Right now:
```js
fitness = 1 - (Math.abs( ( leftValue / rightValue ) - targetRatio) / tolerance)
```

Potentially changed to be based on the position of the "other value." So when the left value changes, calculate the value the left value should be to make the right value in ratio. Then take the difference between the necessary left value, and the current left value. This would make the tolerance have the same spread regardless of the values of the ratio.

**Comment by emily-phet** [comment]
This sounds reasonable to me, as long as it "feels" good at low marker values (i.e., low on the screen). I'd also like to check in with Dor regarding the necessity of starting the grid at 0, which might impact things...

**Comment by emily-phet** [comment]
What if the tolerance was set such that you always get a “2 gridline radius above and below” of feedback. That would mean there would be four gridlines total of feedback (40% of the screen). We’d have to tweak at the edges (if the success point is less than 2 and greater than 8). This is *almost* the feedback range on the current phettest sim if you place the left hand at 3 and move the right hand up and down.

(note to self - when changing tolerance query parameter, I liked it at .25).

**Comment by BLFiedler** [comment]
I definitely like basing the tolerance around the grid spacing. 

Just a note for the continuous movement success feedback:
- We may want to determine a different tolerance for this than the tolerance for in-proportion. I say this because at tolerance=0.2, I can move my hands at _a fixed distance_ for maybe 30-40% of the screen and get the choir-ahh sound. That seems a little too far to give confirmation of the incorrect movement.

**Comment by zepumph** [comment]
In today's sound design meeting. We decided to try out a new tolerance algorithm, in which we have the tolerance be static to .2 on either side of the value changing. This may make smaller ratios (like when both pointers are below .1), but we are not too worried about this, and it will be a large improvement for the larger ratios.

@BLFiedler mentioned that perhaps we can use a piece-wise function in the future to handle the smaller ratios if needed.

**Comment by zepumph** [comment]
The goal of this change is to make sure there is enough "wiggle room" for small devices. Let's test this once it is implemented.

**Comment by zepumph** [comment]
Implementing this ended up being a bit strange. Please review the current behavior and let me know if it is desired. I think I got it, but I am not confident. I think that @emily-phet and @BLFiedler have a better understanding of where the previous tolerance algorithm fell short, so I am interested to hear if/how they feel this is an improvement.

**Comment by zepumph** [comment]
I also updated the doc for the tolerance query parameter if that is helpful, https://github.com/phetsims/ratio-and-proportion/blob/master/js/common/RatioAndProportionQueryParameters.js

**Comment by zepumph** [comment]
I'm really worried about the above commit. There is really buggy behavior when you move both hands and the fitness is 0. This is because the new tolerance algorithm bases the tolerance on the most recently changed value. So when both are changing at once, the tolerance is chaotic. This results in horrible, speaker breaking sounds. I'll try to work out a stop gap right now, but I think we need to talk about the new tolerance algorithm.

**Comment by zepumph** [comment]
It is better after the above commit. Now it is a bit harder to get bad/scratchy sounds. Let's talk more about this.

The issue with having a "static" tolerance, is that the algorithm is calculated differently depending on if you want it to be .2 above/below the left value, or the right value. This means that when moving both at the same time, there is a race condition where both algorithms are fighting for what the ratio fitness is. This can be seen in the code here, where depending on if the left or right value most recently changed, we calculate the ratio fitness differently. 

https://github.com/phetsims/ratio-and-proportion/blob/6564975bc574d490d4e8d6f9853587e05982cc5b/js/common/model/RatioAndProportionModel.js#L92

No solutions yet, but I wanted to mention the problem here so we can work it out together.

**Comment by emily-phet** [comment]
Maybe it would be helpful to think of the task we're trying to accomplish a bit differently. Not sure where this is going...but here we go. 

Rather than focusing on the 1) location of left hand, 2) location of right hand, 3) ratio between them, let's consider 1) the distance between the two hands and 2) the center point of that distance. For any specific distance between the two hands (e.g., 3 gridlines, 4.5 gridlines, etc.) there is a single position for the center point that is success (i.e.., if the distance between the hands is 3 gridlines, then the only place that makes for success in Challenge 1 is if the center point is positioned at 4.5).

Does it help the problem at all if we set a specific range to provide feedback of the *center point* (e.g., when the center point of the distance is between +/- 2 grid lines of of the center point success)?

Not sure if this circles back around to the same issue - since it still requires knowing the position of both hands which may be moving rapidly.

If this doesn't help - perhaps a quick brainstorm with other devs?

**Comment by zepumph** [comment]
I explored an algorithm 

```diff
Index: js/common/model/RatioAndProportionModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/RatioAndProportionModel.js	(revision 85c1d856f048526bdeb118cbb9723bee599a0122)
+++ js/common/model/RatioAndProportionModel.js	(date 1591660787803)
@@ -29,7 +29,7 @@
   constructor( tandem ) {
 
     // The desired ratio of the left value as compared to the right value. As in 1:2 (initial value).
-    this.ratioProperty = new NumberProperty( .5 );
+    this.ratioProperty = new NumberProperty( 1 / 3 );
     this.toleranceProperty = new NumberProperty( RatioAndProportionQueryParameters.tolerance );
 
     // @public
@@ -41,7 +41,7 @@
       tandem: tandem.createTandem( 'leftBarProperty' ),
       validBounds: modelBounds
     } );
-    this.rightPositionProperty = new Vector2Property( new Vector2( 0, .4 ), {
+    this.rightPositionProperty = new Vector2Property( new Vector2( 0, .6 ), {
       tandem: tandem.createTandem( 'rightBarProperty' ),
       validBounds: modelBounds
     } );
@@ -88,25 +88,26 @@
         return 0;
       }
 
-      let fitnessError = null;
-      if ( this.lastChanged === this.leftValueProperty ||
+      const valueDistance = rightValue - leftValue;
+      const currentCenter = ( valueDistance / 2 ) + leftValue;
+
+      const desiredLeft = valueDistance * ratio / ( 1 - ratio );
+      const desiredRight = desiredLeft + valueDistance;
+      const desiredCenter = ( ( desiredRight - desiredLeft ) / 2 ) + desiredLeft;
 
-           // TODO: try to remove this in exchange for a better tolerance algorithm
-           ( this.leftValueProperty.value > 0 && this.rightVelocityProperty.value > 0 ) ) {
-        const expectedLeftValue = ratio * rightValue;
-        fitnessError = Math.abs( leftValue - expectedLeftValue );
-      }
-      else {
-        const expectedRightValue = leftValue / ratio;
-        fitnessError = Math.abs( rightValue - expectedRightValue );
-      }
+      const fitnessError = Math.abs( desiredCenter - currentCenter );
+      console.log( desiredCenter );
+
+      // TODO: ofsetting based on the ratio seems like a good way to normalize this value for all ratios.
       return 1 - Util.clamp( fitnessError / tolerance, 0, 1 );
     }, {
       isValidValue: value => this.fitnessRange.contains( value )
     } );

```

In the above patch I experimented with a "centers" algorithm, and found potential promise, but it still suffered from the same problem as the first algorithm in which changing the left value had a different view tolerance than the right value. 

@chrisklus thought that it may be good to use the first algorithm, and normalize it based on the current ratio/current values somehow. This way the tolerance would be less when the values for a ratio were smaller (so the tolerance would look constant). This originally seemed more complicated, but after the last few hours, I think it is a great next direction for this issue.

**Comment by zepumph** [comment]
After discussing with @emily-phet yesterday, I decided to revert to the old, original tolerance algorithm. I then spent some time last night trying to figure out a function that I could calculate for tolerance based on what the numerator and denominator are for the current and target ratio. It worked for a target of 1/3, but didn't quite cover all ratios yet.

```diff
Index: js/common/model/RatioAndProportionModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/RatioAndProportionModel.js	(revision 30d2e2bc7381f8ca6f1152327fd9cc2e1627fe47)
+++ js/common/model/RatioAndProportionModel.js	(date 1591836327356)
@@ -15,6 +15,7 @@
 import Vector2 from '../../../../dot/js/Vector2.js';
 import Vector2Property from '../../../../dot/js/Vector2Property.js';
 import Color from '../../../../scenery/js/util/Color.js';
+import Fraction from '../../../../phetcommon/js/model/Fraction.js';
 import RatioAndProportionQueryParameters from '../../common/RatioAndProportionQueryParameters.js';
 import ratioAndProportion from '../../ratioAndProportion.js';
 
@@ -29,7 +30,7 @@
   constructor( tandem ) {
 
     // The desired ratio of the left value as compared to the right value. As in 1:2 (initial value).
-    this.ratioProperty = new NumberProperty( .5 );
+    this.ratioProperty = new Property( new Fraction( 1, 2 ) );
     this.toleranceProperty = new NumberProperty( RatioAndProportionQueryParameters.tolerance );
 
     // @public
@@ -80,14 +81,20 @@
         return 0;
       }
 
-      const fitnessError = Math.abs( currentRatio - ratio );
-      return 1 - Util.clamp( fitnessError / tolerance, 0, 1 );
-    }, {
+      const scalar = 1;
+      // target ratio +- 1 = left/right
+
+
+      const ratioError = currentRatio - ratio.value;
+      const normalizedTolerance = Math.abs( ( leftValue * 10 - ratio.numerator ) / ( rightValue * 10 * ratio.denominator ) );
+      debugger;
+      console.log( ratioError, normalizedTolerance );
+      return 1 - Util.clamp( Math.abs( ratioError ) / normalizedTolerance, 0, 1 );    }, {
       isValidValue: value => this.fitnessRange.contains( value )
     } );
 
     // @public - based on the proportion fitness
-    this.colorProperty = new DerivedProperty( [ this.proportionFitnessProperty ], fitness => {
+    this.colorProperty = new DerivedProperty( [this.proportionFitnessProperty], fitness => {
       return Color.interpolateRGBA( INCORRECT_COLOR, CORRECT_COLOR, fitness );
     }, { valueType: Color } );
 
Index: js/challenge-maker/view/ChallengeMakerScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/challenge-maker/view/ChallengeMakerScreenView.js	(revision 30d2e2bc7381f8ca6f1152327fd9cc2e1627fe47)
+++ js/challenge-maker/view/ChallengeMakerScreenView.js	(date 1591836289217)
@@ -46,7 +46,7 @@
       spacing: 10,
       children: [
         RatioHandNode.createIcon( false, this.gridViewProperty, { scale: .8 } ),
-        new NumberPicker( numberatorProperty, new Property( new Range( 1, 10 ) ) ) ]
+        new NumberPicker( numberatorProperty, new Property( new Range( 1, 10 ) ) )]
     } );
 
     const denominatorProperty = new NumberProperty( initialRatioFration.denominator );
@@ -55,16 +55,16 @@
       spacing: 10,
       children: [
         RatioHandNode.createIcon( true, this.gridViewProperty, { scale: .8 } ),
-        new NumberPicker( denominatorProperty, new Property( new Range( 1, 10 ) ) ) ]
+        new NumberPicker( denominatorProperty, new Property( new Range( 1, 10 ) ) )]
     } );
 
-    Property.multilink( [ numberatorProperty, denominatorProperty ], ( leftValue, rightValue ) => {
-      model.ratioProperty.value = leftValue / rightValue;
+    Property.multilink( [numberatorProperty, denominatorProperty], ( leftValue, rightValue ) => {
+      model.ratioProperty.value = new Fraction( leftValue, rightValue );
     } );
 
     const myChallengeContent = new HBox( {
       spacing: 80,
-      children: [ leftRatioSelector, rightRatioSelector ]
+      children: [leftRatioSelector, rightRatioSelector]
     } );
     const myChallengeAccordionBox = new AccordionBox( myChallengeContent, {
       titleNode: new RichText( ratioAndProportionStrings.myChallenge ),
Index: js/explore/view/ExploreScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/explore/view/ExploreScreenView.js	(revision 30d2e2bc7381f8ca6f1152327fd9cc2e1627fe47)
+++ js/explore/view/ExploreScreenView.js	(date 1591836289217)
@@ -10,6 +10,7 @@
 import ratioAndProportion from '../../ratioAndProportion.js';
 import ratioAndProportionStrings from '../../ratioAndProportionStrings.js';
 import ChallengeComboBoxItem from './ChallengeComboBoxItem.js';
+import Fraction from '../../../../phetcommon/js/model/Fraction.js';
 
 class ExploreScreenView extends RatioRatioAndProportionScreenView {
 
@@ -24,9 +25,9 @@
     const comboBoxParent = new Node();
 
     const comboBox = new ComboBox( [
-      new ChallengeComboBoxItem( 'Challenge 1', 'green', 1 / 2, { a11yLabel: 'Challenge 1' } ),
-      new ChallengeComboBoxItem( 'Challenge 2', 'blue', 1 / 3, { a11yLabel: 'Challenge 2' } ),
-      new ChallengeComboBoxItem( 'Challenge 3', 'magenta', 3 / 4, { a11yLabel: 'Challenge 3' } )
+      new ChallengeComboBoxItem( 'Challenge 1', 'green', model.ratioProperty.value, { a11yLabel: 'Challenge 1' } ),
+      new ChallengeComboBoxItem( 'Challenge 2', 'blue', new Fraction( 1, 3 ), { a11yLabel: 'Challenge 2' } ),
+      new ChallengeComboBoxItem( 'Challenge 3', 'magenta', new Fraction( 3, 4 ), { a11yLabel: 'Challenge 3' } )
     ], model.ratioProperty, comboBoxParent, {
       accessibleName: ratioAndProportionStrings.a11y.ratioChallenges
     } );

**Comment by emily-phet** [comment]
Note on priority:
@zepumph - the feedback on fitness seems a little buggy of late, as you're working through changes to tolerance. We'll need this to be at least in a stable consistent place (if not the final state) before interviewing again. 

@Brett - If you haven't scheduled interviews yet, can you please check in directly with @zepumph about this tolerance issue, and depending on how much time he needs, plan to interview as soon as the sim is not giving funny color/sound changes due to tolerance issues. We'll discuss what sounds we want to interview with in the meeting tomorrow, but the sim will need to be giving reasonable and consistent visual/auditory feedback (so the tolerance setup needs to be at least as good as the last few interviews) for us to do that. Sooner is better with interviews for sound/visuals, as we'll be focusing on description soon and you'll want to be able to have some focused time for a new user group.

**Comment by zepumph** [comment]
Today @BLFiedler and I saw that the iPad app written by collaborators has a static tolerance that looks very nice for all ratios. It isn't based on the ratio, but instead is always a certain number of grid lines above and below. I'll look into trying to do that, and if not, then we will, at the very least,  need to alter how the choir success sound plays.

**Comment by zepumph** [comment]
In the above commit. I made the tolerance algorithm exactly the same as the "easy" version of the collaborator app. To calculate fitness, it takes the difference from the current left value and the "desired" left value. Thus, at the default of `.1`, the fitness will be zero on startup after moving the left value up to 5, or down to 3. 

@BLFiedler please review with the following thoughts:

* .1 aka 10% aka one grid line is not very much compared to some of the larger values of tolerance we had looked at before. That said, it is consistent across the whole length of the sim. Is this the value you would like as the default?
* After solving the first bullet, do you want to change the choir fitness threshold? Let me know if you want that to become a query parameter to mess with at all.
* In regards to the collaborator app, do we have a desire in setting multiple levels of difficulty where we change the tolerance to a smaller value to make it "harder"? A UI component for it may work well on the second screen. @emily-phet, this is likely something that you have thought of already (and maybe we have even discussed it). Should we make a new issue to discuss this?

**Comment by BLFiedler** [comment]
We should bring this to everyone and see how it feels to them. I'll add the latest dev link to the slack channel and ask folk to try it ahead of Tuesday's meeting and see if anyone has thoughts.

**Comment by BLFiedler** [comment]
In current iteration (dev28), tolerance algorithm gives success at 0L and 0R for all challenges. This may be unavoidable with a more static tolerance? It's had interesting repercussions during interviews, but I think if we do not change this behavior, we should consider Emily's issue at #65. 

One participant used the success at zero to confirm their multiplicative reasoning (0 x 2 is green for challenge 1, as is 0 x 3 for challenge 2, etc). Otherwise 0L0R seems likes a trap for velocity sound and for finding additional success states (trap in "region success reasoning" as opposed to "relative hand positioning reasoning")

**Comment by emily-phet** [comment]
Seems like we should just disallow this - if 0L and 0R = no success feedback.

**Comment by zepumph** [comment]
As an experiment, and because it was simple, I added logic such that if either value is less than half a grid line, the fitness is zero. This makes for some weird jumps, but I think it makes it clear that we don't want users poking around down there. I'm happy to revert this, but it felt like a minor improvement after hearing how 0 played into interviews. Let me know what you would like.

**Comment by emily-phet** [comment]
Based on our meeting on June 30, I'd like to proceed with the following:
- The lowest point either hand can be located and result in a fitness of 1 is at the hand location 0.5. For hand locations below that point, fitness can be less than 1 and non-zero (showing non-success shades of green), but cannot show success.

Though I'm asking for implementation of this new approach, I'd like to acknowledge that @zepumph did not favor this approach, indicating (I'm paraphrasing) that if a goal is to cue learners to not hang out in the lower regions (below gridline 1) with the hand markers, then providing no feedback there may be preferable. Valid point @zepumph, though given the natural affordances that arise from using the lowest point as a starting point for systematic exploration, I'd like to give this new approach a try.

**Comment by zepumph** [comment]
The above sounds really good to me! I have it in my working copy, and I realize that I will need to work on https://github.com/phetsims/ratio-and-proportion/issues/83 in correlation with this issue, because it won't be enough to make sure fitness doesn't get to the value "1", but instead we will need to match the success thresholds outlined over there.

**Comment by zepumph** [comment]
```diff
Index: js/common/model/RatioAndProportionModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/RatioAndProportionModel.js	(revision df03dfb739ad5c2f6612e838a0b42dec627fd15c)
+++ js/common/model/RatioAndProportionModel.js	(date 1594062679790)
@@ -17,6 +17,9 @@
 import RatioAndProportionQueryParameters from '../../common/RatioAndProportionQueryParameters.js';
 import ratioAndProportion from '../../ratioAndProportion.js';
 
+// The value in which when either the left or right value is less than this, fitness cannot be 1
+const NO_SUCCUSS_VALUE_THRESHOLD = .05;
+
 class RatioAndProportionModel {
 
   /**
@@ -76,12 +79,16 @@
       if ( isNaN( currentRatio ) ) {
         return 0;
       }
-      if ( leftValue < .05 || rightValue < .05  ) {
+      if ( leftValue === this.valueRange.min || rightValue === this.valueRange.min ) {
         return 0;
       }
       const desiredLeft = ratio * rightValue;
       const fitnessError = Math.abs( desiredLeft - leftValue );
-      return 1 - Utils.clamp( fitnessError / tolerance, 0, 1 );
+      const fitness = this.fitnessRange.max - Utils.clamp( fitnessError / tolerance, this.fitnessRange.min, this.fitnessRange.max );
+      if ( fitness === this.fitnessRange.max && ( leftValue < NO_SUCCUSS_VALUE_THRESHOLD || rightValue < NO_SUCCUSS_VALUE_THRESHOLD ) ) {
+        return .9;
+      }
+      return fitness;
     }, {
       isValidValue: value => this.fitnessRange.contains( value )
     } );
```

**Comment by zepumph** [comment]
Above has now been implemented. Please see https://github.com/phetsims/ratio-and-proportion/issues/83#issuecomment-655112681 for next steps and review. I think I'm going to close this issue, and carry on over there. Please reopen if you feel differently.

**Comment by zepumph** [comment]
Today during sound design, we rehashed our current algorithm for tolerance, we didn't discuss the above changes, but instead focused again back on the tolerance itself. We were wondering how the grid lines should change the tolerance. Right now they don't at all, but @emily-phet mentioned that it could be better to have the tolerance change based on the number of grid lines. This way if you are counting grid lines on either side of a correct ratio, then different grid views apply a multiple to the number of grid lines a tolerance will pass. For example, with 1/2 and current tolerance of .1, moving the right hand will yield a tolerance range of 2 grid lines above and below the right ratio with default grid lines. If they are then shifted to 0-30, then you pass through 6 grid lines on either side of the correct ration. Reopening. Assigning to @emily-phet to contemplate.

**Comment by emily-phet** [comment]
@BLFiedler - I still want to think about this a little more, but don't have mental capacity to do so at the moment (I'm too tired...). 
When you consider this, if it's easy to convince yourself that @zepumph and @jbphet were correct, don't work too hard to try to convince yourself otherwise. They're probably right...but I still want to take some time when I'm sharp to think it through.

**Comment by zepumph** [comment]
Please note that lots of experimentation has been done over in https://github.com/phetsims/ratio-and-proportion/issues/91, and currently the direction is to have the fitness be different depending on which hand you move. This is because fitness is based on the ratio, not individual values.
