### ISSUE TITLE
Moving location of help text for Guide Options - to above list

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#150]
Move help text for Guide Options to above list, rather than current location below list.

**Comment by emily-phet** [comment]
For both screens.

**Comment by zepumph** [comment]
@jessegreenberg, last week I feel like we talked about doing something really similar to the above commits, but I don't remember for what issue. Can you please review this refactor and let me know if you have any concerns. The goal is generality and reusability. My hope would be that we start using helpText and accessibleName in 95% of cases, and build out these behavior functions so that once others start using it, there will already be those behaviors for them to use in their cases. Please review.

**Comment by jessegreenberg** [comment]
These functions look great, and I look forward to using them. I remember briefly talking about where to put them but don't think it was solidified. I think they will be hard to find in the `A11yBehaviorFunctionDef`, which (I think) would generally be used for validation rather then definition of behavior. Perhaps I am incorrect about this though.

What do you think about putting these in ParallelDOM.js or perhaps a new file?

**Comment by zepumph** [comment]
I moved to ParallelDOM, which felt best to me for now. When there are more we can move them around to a better spot.
