### ISSUE TITLE
H3 heading "My Challenge" above accordion box on Create screen 

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#151]
See design doc, there is a "My Challenge" H3 heading above the accordion box. Please add this.

**Comment by terracoda** [comment]
@emily-phet, "My Challenge" is coded as a heading level 3 `<h3>`, but it is a button inside a heading, so the styling in the A11y View makes it look like a button, rather than a heading.

Users in interviews were able to find "My Challenge" when looking for a heading or a button, and I think at least one participant commented positively about a button being inside a heading.

Here's the code:
![h3-and-button-my-challenges](https://user-images.githubusercontent.com/1902116/90766162-b026f800-e2c5-11ea-9c58-755f817915d0.png)

Closing, because this is not an issue, just a visual discrepancy/confusion, which also threw me off originally.
