### ISSUE TITLE
Third bulletin for Static screen summary

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/ratio-and-proportion#153]
Basic pattern for all 3 views

Currently, hands are {{proximity-to-ratio}} the challenge {{1}} ratio with 
- Left hand {{hand-position-qualitative or hand-position-ordinal or hand-position-numbered}}
- Right hand {{hand-position-qualitative or hand-position-ordinal or hand-position-numbered}}
- **Hands are {{extremely far from}} each other.**

The third bulletin is new and has a [table ](https://docs.google.com/document/d/1HJvvGWYaUv9tlat9S7omQQVng8fGB4FuUhTEM1qx1z8/edit#heading=h.th029tedybfa)for all the regions 

1. Max distance from 
2. extremely far from
3. very far from
4. far from  
5. not so close to 
6. somewhat close to 
7. very close to 
8. extremely close to 
9. even with

**Comment by zepumph** [comment]
I wrote a comment in the design doc, but is it possible for these regions to be the same as the distance regions in the aria-live alerts? This would mean using the same ranges, and choosing if we want to have "max distance from" or "farthest from" as the last region in both. I went with "farthest from" right now since it is already in from work over in #152. Please review.

**Comment by Matthew-Moore240** [comment]
These are working good. I am okay with it being farthest from, tested extremes and everything is looking pretty good. Closing
