### ISSUE TITLE
Final sound mixing

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#158]
@Ashton-Morris mixed over in https://github.com/phetsims/ratio-and-proportion/issues/127#issuecomment-679388380, and that along with https://github.com/phetsims/tambo/commit/bf323435a704a1b2174d0201918b418a61bfce8f has made a potentially final sound mix for the sim. There is still some cleanup to be done in a few other issues, but the levels should be all set. Assigning for final review of https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.57/phet/ratio-and-proportion_all_phet.html.

**Comment by jbphet** [comment]
I tried the mix out on headphones, on a pair of Altec-Lansing "Multimedia" computer speakers (with no subwoofer), and on the built-in speakers of my Dell XPS laptop.  For the most part, I thought the relative levels were great.  The only suggestion I would make is to slightly reduce the level of the getting-closer-pluck sound.  It seemed a little loud to me in all cases, especially since it plays so frequently, but I noticed it more on the external speakers than in the headphones.

**Comment by jbphet** [comment]
One other thing related to common-code UI components: I think the open and close of the accordion box is a little loud and we should consider reducing it.  I believe this is the first sim that will be published with sound enabled for this component, so we should be free to make changes without worrying about the impact on other sims.

**Comment by emily-phet** [comment]
Question - should we hear the tick mark sounds (the little 'bump' sound as hands move past the tick marks) when we're also hearing the choir sound. For example, with lock ratio checked and tick marks showing, you hear both the choir sound and the tick mark sound as you move hands up/down.

**Comment by BLFiedler** [comment]
Sound levels generally seem fine to me. Defer to others on most of UI sounds. They generally don't play while you're playing with the sim, so volumes don't seem too problematic to me.

re the tick marks during choir: It seems like tracking the tick mark sounds and the choir at the same time might be kind of difficult, but auditorily it seems like it's analogous (but missing some dimensionality) to visually the passage of the tick marks to achieve the choir sound. I am not very good at tracking multiple cues like that, but perhaps it's worth seeing if any of the BVI users find it useful to have both?

**Comment by terracoda** [comment]
Hand interaction
 - focus sound for hands much quieter than radio button sounds. Not sure if that is intentional, it might be.

Screen buttons in bottom bar
- like sounds on home screen when going from button to button. Does it make sense to do the same thing in the bottom bar?
- like different sound for going back to Home screen.

Challenges combobox
- there are no sounds for 3 challenges. Is that intentional? We have item sounds in Molarity, though solutions are perhaps more critical to that sim??

Screen 2 - the number spinners are very quiet.

**Comment by zepumph** [comment]
- [ ] Staccato sound quieter 
- [ ] UI tick mark bumps off when locked ratio
- [ ] Move it behind the "enhanced sound" option
- [ ] Don't mute the pickup/drop sounds when in staccato feedback range, just the tick mark bumps


RE: @terracoda's comment:

>focus sound for hands much quieter than radio button sounds. Not sure if that is intentional, it might be.

Since they are fundamental interactions, we like them being a bit quieter so they don't get annoying.

>Screen buttons in bottom bar

Two different sounds are because it is two different interactions. The home screen buttons are first highlighted before getting selected, but the nav bar buttons are immediately selected.

>Challenges combo box

The sound design meeting hears three (slightly) different sounds taken from molarity used for the first screen combo box selections. You don't get a sound if you select the same element that is already selected.

>Screen 2 - the number spinners are very quiet.

The sound team noted this and thought the same. @emily-phet thinks that we should leave this for now and then in the future when we get more interviews with description (with screen reader users), we should ask to see what those learners think.

-----------------------

@zepumph mentioned that the drop sound and the pickup sound play at the same time when the ratio hands are tabbed between each other. @emily-phet recommends waiting to see and asking during interviews.

**Comment by zepumph** [comment]
Everything has been done above. @BLFiedler will you please do a final review and make sure all is good. 

RE: these three bullets:

```
UI tick mark bumps off when locked ratio
 Move it behind the "enhanced sound" option
 Don't mute the pickup/drop sounds when in staccato feedback range, just the tick mark bumps
```

We only talked about 2 UI sounds during the conversation: tick bumps and pickup/drop, but there is a third that happens when you boop the boundary of the vertical range. That sound is not an enhanced sound, and it still plays when the ratio is locked. 

Over to you @BLFiedler.

**Comment by BLFiedler** [comment]
I think the boop is still informative with the ratio lock (you've hit the edge with a hand which is why you can't move any farther).

All checks out to me. Was able to identify all of the changes listed above. Woohoo! Over to zepump to close if there's nothing else  and to check off for the sound checklist.

**Comment by zepumph** [comment]
>Over to @zepumph to close if there's nothing else and to check off for the sound checklist.

That will be done over in #127.
