### ISSUE TITLE
Scaffolding Screens

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#16]
Dor (from Design Doc)
>Our approach to the Bars situation should be as a direct continuation of the cursors-only. Think of bars as turning location (my hand is 'here') to quantity (my hand is 'so' far from the bottom). To the extent possible, students should be moving from cursors-only to bars to bars-and-grid to bars-and-grid-and-numbers to 'driver' (if we choose to use that) as a continuity of concatenated experiences, ideally in that order, but also with flexibility of going back and forth.

_Originally posted by @BLFiedler in https://github.com/phetsims/proportion/issues/15#issuecomment-613019563_

**Comment by emily-phet** [comment]
@Dor we should discuss the interaction flow for the sim again. It matters a lot whether for the typical sequence of learner interaction whether things are in the first screen, second screen, or consolidated into one screen. Let's set up a time for a quick phone call on this.

**Comment by emily-phet** [comment]
@zepumph 

I discussed with Dor - please remove the bars screen altogether.

**Comment by zepumph** [comment]
I removed it above. As for the code, I kept the super types split out into common. @emily-phet can you comment on the chances of us adding another screen at some point in the future?

**Comment by emily-phet** [comment]
@zepumph I'd say it's too soon to tell about a second screen. Give us a few more weeks, and I think it will be more clear. 

There's always the possibility that other math PhET folks may want to extend the sim, though...so there may be at least a small chance of extending the sim for quite awhile. Might be best to plan for the possibility existing for the long term, though again, my aim would be to settle in the next month or so if there will be a second screen in the short term (i.e., this year).

**Comment by zepumph** [comment]
Sounds very reasonable. I have the following two conflicting thoughts. 

1. Desire to not spend time pre-maturely optimizing when we may be changing designs drastically.
2. Recognizing that most of the time it is much easier and less costly to improve code as we go rather than to go back later and refactor. 

Given the fact that things are so up in the air. I think that prioritizing (2) makes sense here. We don't even know if the current hierarchy would work with the screen design in the future. It seems best to improve as we go. I will do that here.

**Comment by zepumph** [comment]
I'm happy with the commits above. I added a few TODOs that I didn't want to dive into just yet (in part recognizing (1) above). There is now only one screen and no factored out common model/view stuff. Closing
