### ISSUE TITLE
Some target ratio + one hand position yields impossible other hand with smallest keyboard step

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#175]
Wow. confusing title. This is coming from discussion during today's sound design meeting, as well as a review that @BLFiedler did in https://github.com/phetsims/ratio-and-proportion/issues/162#issuecomment-685229934. 

To reproduce:
* Second screen
* Target ratio of 1/5
* Right hand at 9.4
* Left hand can't get to ratio, but closest is 1.9

@emily-phet, @jbphet, and @BLFiedler discussed and definitely feel like this is no good. To create an equitable experience for keyboard users, we should never be in a case where the model can't get "in proportion" from an input modality.

There were multiple solutions brainstormed:
* Detect this case, and add an extra step in between two shift key steps that is in Proportion
* Increase the "in proportion" range to account for all of these cases.
* Decrease the shift keyboard step size to account for all of these cases.
* Detect this case, and provide a "snap-to": solution that that also allows for a "conservation of the number of steps" between two tick marks. We want to try this out first, even though I'm unsure how ugly the implementation will be. @BLFiedler offered to provide a bit more detail on this before I implement.

**Comment by BLFiedler** [comment]
I will try to detail this without being more confusing and correct me anywhere I mess up the details of what's currently in place.

During normal exploration, a keyboard user can use the coarse increment (Up/Down for single focus) to move a hand or the fine increment (Shift+Up/Down). The fine increment moves along a defined grid such that there are 10 keypresses between integer tick marks (0-10 range). Because step sizes are discrete, but target ratios are continuous, it is possible to "Step-over" the target ratio in some configurations of the left and right-hand positions. 

@emily-phet made several points on the importance of conserving button presses during exploration (especially when there is little (quantitative in this case) information to determine why something changed).

The "snap-to" solution _conserves button presses_ by snapping to the target ratio when it would otherwise be bypassed, treating it as though it were the next grid line (faux-grid line), and on the subsequent keypress (in the same direction), bypass the next tick mark and re-align to the grid. **In essence, the target ratio snap behaves like the grid line that was or will be skipped over**. I believe this creates 3ish cases.

Let's consider an example where the left-hand moves along the pre-defined grid in **0.1 increments from 1 to 2**, while the right-hand remains fixed at some higher value. The target ratio is achieved when the left-hand is at **1.55**, which is not in the range of left-hand increments. By treating the target ratio as a 

- **Up:** Example values for the left-hand with 5 Up keypresses around the target ratio would be: 1.4 -> 1.5 -> 1.55 -> 1.7 -> 1.8. 
- **Down:** Example values for the left-hand with 5 Down keypresses around the target ratio would be: 1.8 -> 1.7 -> 1.6 -> 1.55 -> 1.4. 
- **Turn-Around** (might need to be sub Up & Down as well): Stops at ratio and goes in the other direction. e.g., Up, Up, Up, Down, Down: 1.4 -> 1.5 -> 1.55 -> 1.5 -> 1.4  _OR_ Down, Down, Down, Up, Up: 1.7 -> 1.6 -> 1.55 -> 1.6 -> 1.7

@emily-phet should check me on that, because we did not consider the turn-around case while I was on the call, but I believe adds some extra challenge for @zepumph to implement, as we should not skip over the value if they reverse direction after finding the target.

**Comment by emily-phet** [comment]
@zepumph Is this waiting for implementation, or waiting to be decided if we should do this? Let me know if you'd like to talk through this further.

**Comment by zepumph** [comment]
It is totally on me. I think it is going to be hard so I have been putting it off :). It is on my radar though!

**Comment by zepumph** [comment]
I feel like this is something that should occur at each location in which the view is changing model values. I don't think it makes sense to but this logic into the model, as it would in part involve baking in what input modality the value changes as a result of. This is not ideal.

Thus we are stuck calculating ideal in-proportion values from the view. This also feels very unfortunate, as I don't know how to do this without breaking the entire MVC that this sim has. I'll keep thinking.

**Comment by zepumph** [comment]
@samreid met with me today to discuss this issue, and we thought about a lot of solutions. We ended up feeling like this behavior needed to be supported by each input modality that wanted to support it, because each has a different delta that would need to be conserved. Thanks @samreid for the really productive and helpful conversation for this hard problem!!

In the above commit, logic for this was added to the individual sliders. It didn't play well with the recent adjustments we did to snap keyboard input back to the "grid" after mouse input. 

This commit feels really half-baked to me, but I was able to get the feature working, and some unit tests around it, so I thought I would try to move this issue forward. 

@samreid, the best part about this commit is how I was able to hide the use of `model` and `RatioComponent` into a closure passed to RatioHalf and RatioHandNode. Everything else seems really fragile, and I'm excited to look at it with fresh eyes next week!

**Comment by zepumph** [comment]
I'm feeling more confident about the current behavior for the individual sliders. The main issue, which caused some CT problems, was from javascript rounding. If you look in the repo now, there are 18 usages of `Utils.toFixedNumber( . . . , 6 )`; I created https://github.com/phetsims/ratio-and-proportion/issues/243 to work on that.

Next I'll add this to both-hands interaction.

**Comment by zepumph** [comment]
Both hands is working well above. I think I am ready for design feedback. There are still some tricky edge cases and loose ends, but I want to see if the base behavior is working, and also to check in with how important some of these special cases are. 


* If the input snaps to the in-proportion value, then the remainder is noted, if you reset the sim right then, the remainder not be cleared, and will likely be added next key press.
* The same as above, but for interacting with a mouse in between keyboard input that uses this "snap-to-in-proportion" functionality
* How should this feature mix with the region close to zero where in-proportion can never occur in the model. Right now it doesn't respect that. In the code this is related to `RAPModel.valuesTooSmallForSuccess()`

**Comment by zepumph** [comment]
Here is a case that seems a little bit weird. The "conservation of keypresses" feature behaves strangely when you move up and down on one side of the in-proportion value. Here is an example:

1. Create screen
2. challenge ratio to 2:7
3. select left ratio
4. *repeat as needed* three key presses down, three key presses up.

As you do this, you can see that when you change directions, I kinda expect to go "back" to a certain value, but instead it maps to a different value. This is confusing, but likely less so that to not have conservation of keypresses through the in-proportion value moving in the same direction.

There are not 4 things to work on and/or discuss for this issue.

**Comment by BLFiedler** [comment]
Hm. I think we should talk about whether this behavior happens all the time or only on the small steps. I think I envisioned this behavior only happening when you were fine tuning and not as a replacement for needing to use the small steps to find the ratio. Not sure if I am the only one that was thinking that though.

Not sure if that addresses your concerns, but above occurred to me as I played with it.

**Comment by zepumph** [comment]
During design meeting. . . .

>RE: https://github.com/phetsims/ratio-and-proportion/issues/175#issuecomment-730096193

 we decided to make this change, it was failing a unit test though so I didn't commit:

```diff
Index: js/common/RAPConstants.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/RAPConstants.js	(revision 9e4a7d2eca9309a13b42ca910e06939ae47dc627)
+++ js/common/RAPConstants.js	(date 1606244517911)
@@ -48,7 +48,7 @@
     return ( newValue, oldValue, useShiftKeyStep ) => {
 
       // Don't conserve the snap for page up/down or home/end keys, just basic movement changes.
-      const applyConservationSnap = Utils.toFixedNumber( Math.abs( newValue - oldValue ), 6 ) <= keyboardStep;
+      const applyConservationSnap = Utils.toFixedNumber( Math.abs( newValue - oldValue ), 6 ) <= shiftKeyboardStep;
 
       // TODO: what if there is a remainder and then you use mouse input?!?! https://github.com/phetsims/ratio-and-proportion/issues/175
       if ( remainder === 0 ) {

```


RE: https://github.com/phetsims/ratio-and-proportion/issues/175#issuecomment-729292704

We decided we do need to support the reset case.


>How should this feature mix with the region close to zero where in-proportion can never occur in the model. Right now it doesn't respect that. In the code this is related to RAPModel.valuesTooSmallForSuccess()

For  this we can keep it as is, because no output modality will say we are "at ratio", and the consevation of keypress remainder is really small.

**Comment by zepumph** [comment]
I handled reset on blur and resetting. I also made this behavior only for shift key stepping. @BLFiedler, would you like to double check and see if there is anything else to do here?

**Comment by BLFiedler** [comment]
Double-checked and it looks good according to our conversation yesterday. I think this particular issue is done!
