### ISSUE TITLE
Cue arrows for freely moving cues?

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#18]
From https://github.com/phetsims/proportion/issues/7#issuecomment-612959273. @BLFiedler mentioned perhaps using Faradays Law style arrows:

![image](https://user-images.githubusercontent.com/6856943/79262372-ab48c800-7e3d-11ea-84fa-ee2b517abe63.png)

**Comment by BLFiedler** [comment]
Just a note from the two interviews I did where I included this sim - They were pretty quick to pick up on the fact that those lone two items in the middle of the screen could be moved. Might not need too much cuing.

**Comment by emily-phet** [comment]
@zepumph - Please add up/down only cueing arrows, that appear on first focus / hover, and do not appear again after that (unless reset all is pressed). 

@BLFiedler - From past experience with a few other sims, what can happen without initial visual cueing of motion on non-standard interactive objects (things that are not buttons, sliders, etc.) is that some learners will interact with all/some of the standard interactive objects first. When this sim gets it's final radio buttons, dropdowns, etc., some percentage of people will likely interact with those first, and a visual arrow cue on the free moving objects can reduce that. 

What I think is happening in your interviews is that you have only the two spheres, and a set of one of the least (initially) attractive of all standard interactive objects available to the learner (radio buttons). The aqua radio button styling is kind of "old fashioned" and less attractive. Once the options are "prettied" up, with icons, etc. they may become more attractive. 

Interacting with the standard interactive options first is problematic, as it may cause the learners' first interaction with the free moving objects to be in a more challenging state than when in the default state. So, if a visual cue on the free moving objects does no harm, then it's worth adding in. Let's give them a try and search for a "do no harm" arrow cue design.

Also, some younger kids and learners with cognitive impairments (from past interview observations) may be more likely to "tap" or "click" non-standard interactive objects rather than drag, so the visual arrow cues also help with that.

**Comment by zepumph** [comment]
@emily-phet I implemented a first pass at cue arrows, though I'm quite sure I didn't implement them exactly as you described above. 

I made them just like the behavior of the cue arrows in friction and faradays-law. Would you please describe specifics if you want them to instead be shown on hover/highlight. My main question there was if only a single set of cue arrows highlights at a time, or if both do, and if triggering one then effects the behavior of the other. 

I'm happy to implement whatever you think is best, I just felt like this was a good starting point until I understood things more fully.

**Comment by emily-phet** [comment]
@zepumph I don't see this in the sim yet (using latest on phettest). Please have up/down arrows only, appearing on initial hover/focus. Arrows appear for both cursors whenever shown, and once one is interacted with both disappear.

**Comment by zepumph** [comment]
This is what I see on phettest this morning (after some work in other issues):

![image](https://user-images.githubusercontent.com/6856943/79898022-04bd7380-83b7-11ea-9054-9828a8e049d2.png)

**Comment by zepumph** [comment]
I added support for cue arrows showing only on focus or hover before first interaction. Please review.

**Comment by emily-phet** [comment]
@zepumph Please make each arrow 30% shorter, the color 20% more transparent, and remove the black outline.

**Comment by zepumph** [comment]
I did everything above and I like it much more. The only last thought I have is if the tail should be narrower, I could go either way, but didn't alter it when I made the arrow shorter.

**Comment by emily-phet** [comment]
@zepumph This looks great! 

One thing I intended, but hadn't noticed wasn't there until @BLFiedler mentioned it Friday...

The arrows should appear onscreen when the sim opens, and persist until a marker is moved. It should not rely on hover to appear. 

Apologies for the confusion, most (all?) PhET arrow cues like this one are indeed based on hover behavior...but I was intending something more like the boxes over John's hand/foot in John Travoltage, that provide a constant cue on opening until a specific action is taken.

This approach addresses cueing to move markers across devices, and is not reliant on hove behavior being possible.

**Comment by zepumph** [comment]
Sounds great! I removed the hover logic, and they now are displayed on startup. Anything else here?

**Comment by emily-phet** [comment]
@zepumph looks great! Closing.
