### ISSUE TITLE
ResetAllButton doesn't look depressed when clicked with keyboard

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/ratio-and-proportion#184]
I noticed this while testing another issue. I think it is caused by `interruptSubtreeInput` in the reset listener. This interrupts the PressListener itself and stops the `a11yClickingProperty/looksPressedProperty` from running the timer to looked pressed from an PDOM click.

Instead of calling interruptSubtreeInput on the ScreenView would it be possible to do it on a subtree that has everything except the ResetAllButton?

**Comment by zepumph** [comment]
I am worried about this implementation, is this new because of work done in https://github.com/phetsims/scenery/issues/1076? calling `interruptSubtreeInput` in reset has become a standard (see https://github.com/phetsims/simula-rasa/blob/61b80f1febdd6e7f80bdb46de243f6891409e71d/js/simula-rasa/view/SimulaRasaScreenView.js#L30). Note I didn't add this, but just got it from creating the sim repo. If we can't think of a way around this for a11y, then we should probably mark for dev meeting to see about the feasibility of changing this for all sims. 

First though do you think that we could find a way around this? In `ResetAllButton` perhaps we could use a specific case to support the pressListener for that button specifically? Want to discuss in person tomorrow?

**Comment by jessegreenberg** [comment]
No, this is unrelated to https://github.com/phetsims/scenery/issues/1076. I didn't realize that interrupting the entire ScreenView was becoming a standard.

Another option could be changing the behavior of PressListener from this (in `click`)
```js
      // press or release listeners may have interrupted this click, if that is the case immediately indicate that
      // clicking interaction is over
      if ( this.interrupted ) {
        this.a11yClickingProperty.value = false;
      }
```
to have some minimal "looks pressed" duration.  Lets discuss today!

**Comment by zepumph** [comment]
@jessegreenberg and I discussed this, and decided that changing the behavior of `PressListener.click` when the listener callback interrupts itself was the best way forward. Committed above. Fuzzing is passing. Closing
