### ISSUE TITLE
New hand design for RaP

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#185]
@clmccutchan Can you take a look at this issue - https://github.com/phetsims/ratio-and-proportion/issues/99 - and sketch one or two new hands? 

I'm not sure of your schedule, etc. so could you let me know if you could take this on and how quickly you might be able to do it? We're hoping to iterate on some new hand designs over the next week or two if that's possible.

**Comment by clmccutchan** [comment]
@emily-phet Do you need me to redesign the hands? I wasn't quite sure from the thread above.

**Comment by terracoda** [comment]
Design changes to hand:
- elongate the see-through window
- round the bottom
<img width="157" alt="Screen Shot 2020-09-29 at 2 57 05 PM" src="https://user-images.githubusercontent.com/1902116/94594561-296e1f00-0264-11eb-960f-c1d5876472b9.png">
- @zepumph needs an SVG

**Comment by amanda-phet** [comment]
How is this for hand shape @terracoda ? 
![image](https://user-images.githubusercontent.com/7852916/94845916-9fe25c80-03dd-11eb-84ce-80c7150658c2.png)
![image](https://user-images.githubusercontent.com/7852916/94846111-d91acc80-03dd-11eb-834d-d72cd7a86e1e.png)

**Comment by amanda-phet** [comment]
I just realized the circle in the hand is probably not in that location because you liked it, but probably because it's in the center. So here is the new hand with a dot that is accurately centered. 
![image](https://user-images.githubusercontent.com/7852916/94863363-949c2a80-03f7-11eb-9be3-2d220c0d0c73.png)

**Comment by terracoda** [comment]
@amanda-phet, I think the center of the circle is supposed to align with the tip of the thumb so either the center of the circle or the thumb can be used to align with the tick marks.

I think that means the circle should be moved up a bit.

Can others comment, @BLFiedler, @Matthew-Moore240, @zepumph?

**Comment by BLFiedler** [comment]
@amanda-phet, yeah, for now, I think we'll aim to have the circle center line up with the highest point of the thumb so that touchscreen users still have something to line up even if they are covering the transparent circle with their finger. This makes for a strange placement of the circle for sure, but we will likely explore alternative hand shapes sometime later down the line.

Thanks!

**Comment by amanda-phet** [comment]
Gotcha. 

@zepumph here are the two svg hands! 


[new hands.zip](https://github.com/phetsims/ratio-and-proportion/files/5349859/new.hands.zip)

**Comment by zepumph** [comment]
old:
![image](https://user-images.githubusercontent.com/6856943/95620499-c1b29380-0a1c-11eb-91b3-7f9bc90094ec.png)

new: 
![image](https://user-images.githubusercontent.com/6856943/95620538-cf681900-0a1c-11eb-9b1d-da5e15f181e1.png)

The transition was very simple and easy. Please review. Even though there may be some tweaks here, since the shapes are in SCENERY/Path format now, we can unblock #57 and work on that now.

**Comment by emily-phet** [comment]
@zepumph Looks great to me!
