### ISSUE TITLE
Edge sounds and tick mark bump sounds not heard with keyboard naviagation

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#197]
I noticed in #174 that I was not hearing all the sounds when using a keyboard.

I don't hear tick mark sounds, an enhanced sound, nor do I hear the top and bottom edge sounds (not an enhanced sound).

I am using Safari browser on mac book pro, high sierra 10.13.6.

**Comment by terracoda** [comment]
Added @jbphet, as I am actually not sure who needs to fix this issue.

**Comment by jbphet** [comment]
I'll leave this to @zepumph since he's the primary developer and I don't think this is a problem with the sound library.

@zepumph - there are examples of sound being played in keyboard listeners in, I think, friction, gravity-force-lab, and probably a few other places if you need them.

**Comment by zepumph** [comment]
The above refactor will make the addition of keyboard sounds very easy,

**Comment by zepumph** [comment]
This is working for individual interactions now, but not for the both-hands. I think I will need to move these sounds out to the screen view, and pass them into the ratioHalfs and the both hands interaction so they can be used in each. Also note that because of https://github.com/phetsims/ratio-and-proportion/issues/218, I'm going to be doing this for all sounds in RatioHalf.js

**Comment by zepumph** [comment]
Ok there are now boundary, tick mark, grab, and release sounds in the Both hands interaction. @terracoda please review the sound as it pertains to alt input.

I'm especially interested in how you like the boundary sound behavior.

**Comment by terracoda** [comment]
I can hear all the sounds  now. Thanks @zepumph!

**Comment by zepumph** [comment]
Excellent, I have a bit more code cleanup.

**Comment by zepumph** [comment]
Alright, cleanup complete. Closing
