### ISSUE TITLE
RatioAlertManager.alertRatioChange doesn't use an Utterance

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#220]
In https://github.com/phetsims/ratio-and-proportion/issues/214#issuecomment-717343425, @terracoda said:

>@zepumph, just noting that when using the sliders on VoiceOver, all the context responses containing distance from other hand and proximity to ratio pile up easily, too.

This is likely because there is no utterance, and so there is no alertStableDelay. Likely this should be the same as all context responses that talk about the ratio (1000?).

Furthermore, I was surprised that this wasn't handled by AccessibleValueHandler, and perhaps we want to pack this into the RatioHandNode option called `a11yCreateValueChangeAlert`, which is a more common code approach to supplying sliders with the context response. In regards to this, please see https://github.com/phetsims/scenery-phet/issues/637

**Comment by zepumph** [comment]
@terracoda, the build up should now be solved. We are using AccessibleValueHandler's build-in support for the context response now.

Please review.

At meeting next week I would like to double check one question I had while working on this part. The context response for individual hands has extra logic that won't alert a repeat context response. This seems particular to the qualitative regions, since a region could have multiple keypresses to traverse its space. I'd love to touch base and gauge the importance of this. We aren't handling this generally, and most of the time I don't think about this case at all. It would be nice to know (a) if it is still needed in this case, and (b) if so, if there are other spots we should think about. If this didn't make sense, then no worries. I'll bring it up next week.

**Comment by zepumph** [comment]
>At meeting next week I would like to double check one question I had while working on this part. The context response for individual hands has extra logic that won't alert a repeat context response. This seems particular to the qualitative regions, since a region could have multiple keypresses to traverse its space. I'd love to touch base and gauge the importance of this. We aren't handling this generally, and most of the time I don't think about this case at all. It would be nice to know (a) if it is still needed in this case, and (b) if so, if there are other spots we should think about. If this didn't make sense, then no worries. I'll bring it up next week.


We discussed a lot about potentially detecting this duplicating case and offering a slightly different alert, like manually swapping in "Farther from" for the distance part. For now though, we think leaving it as is is best. We can make these sorts of tweaks after we learn more during interviews.

**Comment by zepumph** [comment]
Now just have a look at the build-up of alerts when using the individual hands.

**Comment by terracoda** [comment]
@zepumph, I just experience the "special logic" you mentioned in https://github.com/phetsims/ratio-and-proportion/issues/220#issuecomment-721314046. I documented this in the design document. It only seems to happen with the right hand slider when ratio is locked.

I do think there is potential here for swapping in the distance-progress string rather than having a silent region. Marking this for further discussion at today's design meeting.

**Comment by zepumph** [comment]
We discussed this at the meeting today, and @terracoda will think through  supplying  closer/farther distance logic with a proximity to ratio context response when the normal context response would duplicate (instead of not supplying anything).

**Comment by terracoda** [comment]
@zepumph, explained the current logic
1. First step or change in direction -> replace qual-distance-region with distance-progress 
2. When the whole context response repeats - don’t do anything (no distance region & no proximity to ratio)

@zepumph,  I see 2 possible paths forward:
**Option 1: Tweak responses based on the same logic:**
1. For changes in direction -> replace qual-distance-region with distance-progress 
2. When the whole context response repeats -> replace qual-distance-region with distance-progress

**Option 2: Use different, but MAYBE super simple logic:**
1. When the qual-distance-region repeats -> replace qual-distance-region with distance-progress
  - Reasoning: MK, because we have some small distance regions with just 1 or 2 default key presses I am wondering if better logic might be replace a distance region with distance-progress if the distance region is the same. We want to be sure to hear the single-value distance regions. I think this would mean removing the change in direction logic and to just test or listen for a repeat qual-distance-region, and swap in a distance-progress

2. Remove logic for changes in direction (if not immediately possible, we could keep it for now and remove later if needed). 
  - Reasoning for removal: the first step or a change in direction might be a new region which might just be one key press (almost even). I don’t want to miss that region. See imaginary example in bottom of qualitative distance regions table. Other possibility is to not replace a single-value or single keypress region with the distance-progress.

@zepumph, I am wondering if option 2 is nice path (i.e. simpler logic) for the long run, but maybe not the path we want to take at this moment in time.

**Comment by zepumph** [comment]
I like option 2, I'll implement that unless you say otherwise.

**Comment by terracoda** [comment]
See related issue #262 which is contains continued thinking on the logic related to design changes in #245.

**Comment by terracoda** [comment]
@zepumph, apologies for not connecting this issue with #262, sooner.

**Comment by zepumph** [comment]
Does this mean this issue should be closed, because it will be covered by the spec outlined in #262?

**Comment by terracoda** [comment]
Yes, work on this issue will continue in #262. Closing.
