### ISSUE TITLE
Reset All bug on second screen - potentially causing issue with My Challenge ratio

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#251]
Some combination of interactions on the second screen, including checking the locked ratio button and selecting reset, caused an issue where the My Challenge ratio was NOT 1:2, but the hands seemed to be stuck in 1:2 (showing green at 1:2 ratio, moving with 1:2 ratio when Lock Ratio was selected, etc.). The screenshot is an example I got at least twice, though I couldn't reliably reproduce what was causing this (more likely due to parenting at the same time as trying to reproduce the issue, not necessarily that the issue is necessarily tricky or random). 

A clear but is that Reset All did not always reset the My Challenge ratio, so my inkling is that it is tied to this.

<img width="1275" alt="Screen Shot 2020-11-23 at 8 02 14 PM" src="https://user-images.githubusercontent.com/5109055/100047248-dda0a780-2dc6-11eb-8762-3fa8003eb91d.png">

**Comment by zepumph** [comment]
I can't seem to reproduce this, but I also think that https://github.com/phetsims/ratio-and-proportion/issues/249 is likely a fix for that, since that fraction is now based on the actual target, instead of whatever the starting values of the hands are. I feel about 60% that this bug may be a side effect of that, and fixed now. 

@KatieWoe could we request some help from QA for this? On master, second screen, likely using the "lock ratio" feature (only enabled while in proportion), can you get the sim into a state where pressing the "reset all button" doesn't properly reset the "My Challenge" number pickers back to 1:2?

**Comment by KatieWoe** [comment]
I haven't been able to reproduce this on master. I spent about 10 minutes trying both with mouse and with keyboard nav. But I also tried an old dev version and couldn't replicate it there either, so I'm not sure if it is still an issue or not. I'll try for a little while longer though. @emily-phet would you want to pair on this issue at some time?

**Comment by emily-phet** [comment]
Agreed - I can't reproduce this now, either. Maybe #249 did the trick! Closing.
