### ISSUE TITLE
Range and the enhanced Tick Mark Sound

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#255]
I just noticed that I hear the enhanced tick mark sound on every step when range is set to 0 to 30 even though the step size is 1.5 tick marks. With range set to 0 to 30, the hand lands on a tick mark every other step.

I'm not sure if this is actually an issue because I am not clear on what the sound is supposed to indicate, i.e. passing a tick mark or landing on a tick mark. In other ranges, the sound is associated with the hand landing on a tick mark.

Is this a bug? When is this enhanced sound supposed to play?

**Comment by zepumph** [comment]
I thought that it was passing a tick mark, over to @emily-phet for recommending how to proceed.

**Comment by emily-phet** [comment]
Hey folks - here's the link to the sound design doc, which lists out all of the sounds and when they play. https://docs.google.com/document/d/1dSfPP5JnaQX2Z4lKn7DdSWSuzCLijoNUFvpW_nnR-7s/edit?usp=sharing

The tick mark sound is intended to happen as you pass a tick mark.

I'm not sure if this means the behavior at 0-30 is fine, but behavior elsewhere is not, or if this means there isn't a bug.

@terracoda Once @Ashton-Morris returns, try reaching out to him directly about questions regarding the intended sound behavior. It seems like an outcome of your not being in all of the sound meetings (mainly due to scheduling challenges...there's not enough morning overlap time on Tuesdays!), means you're having questions about the sound design very late in the process. @Ashton-Morris will know generally what was intended, though not necessarily the specifics of how it was implemented or how firm or changeable any current decision is. Start with checking with him about the intended sound. 

Something that may help as well is before we pause sonification meetings on a sim (when we think the sound design is essentially done, but the rest of the design is not), we should just have a meeting with every team member synchronously, go through all of the sounds and logic in the sim and the sound design doc, that way everyone knows what is intended. 

I totally get it's hard to keep track of these things, especially when different sounds follow different logic...if you weren't directly in those discussions you wouldn't know those details, and you can't ask questions about things when you don't yet know they exist. :)

**Comment by terracoda** [comment]
This is not a bug. I think it is implemented correctly. The hands are either passing or landing on a tick mark. 

When using the shift key, I only hear the tick mark sound when I actually pass the mark.

@emily-phet, thanks for sharing the Sound design doc. In addition to your explanation, the design doc was helpful.

Closing.
