### ISSUE TITLE
A11y page website description text

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#260]
We plan to publish a dev version to the a11y page, and will need associated text written.

**Comment by terracoda** [comment]
@emily-phet, how is this for a description for the website:

"With our first accessible math sim, play with the left and right hands in diverse ways to explore and discover a challenge ratio. On the Create Screen, create your own challenge to explore deeper and verify concepts around ratio and proportion."

**Comment by zepumph** [comment]
@emily-phet  we may be past this, since we are about to publish the sim fully. Can this issue be closed? Or perhaps I don't understand this issue's purpose fully.

**Comment by emily-phet** [comment]
How about:
"Play with the left and right hands in different ways, and explore ratio and proportion. To get started, on the Explore screen, find each challenge ratio by moving the hands. Then, on the Create screen, set your own challenge ratios. Once you've found a challenge ratio, try to move both hands while maintaining the challenge ratio." 

It's a bit verbose, and I'm going from memory (maybe the screen names are different now). What do you think? 
This one is tricky, since the users input mechanism matters a lot!

**Comment by terracoda** [comment]
Yep screen one is "Discover". I think your description is good. It provides all the learning pathways.

I'll adjust it slightly because of the "Discover Screen" name. How's this?

 "Play with the left and right hands in different ways, and explore ratio and proportion. Start on the Discover screen to find each challenge ratio by moving the hands. Then, on the Create screen, set your own challenge ratios. Once you've found a challenge ratio, try to move both hands while maintaining the challenge ratio."

**Comment by terracoda** [comment]
@emily-phet is the new text in https://github.com/phetsims/ratio-and-proportion/issues/260#issuecomment-761875687 ok by you?

**Comment by terracoda** [comment]
Actually, I have posted this on the A11y Sims page.
Please close issue, if the description is good as is :-)

![Screen Shot 2021-01-17 at 5 14 27 PM](https://user-images.githubusercontent.com/1902116/104855477-9119aa00-58e7-11eb-9719-4f363c557020.png)

**Comment by emily-phet** [comment]
Looks good!
