### ISSUE TITLE
review pointer areas

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#271]
General issue from code review. @emily-phet can you please take a look at the sim with `?showPointerAreas` and let me know what you think. There was an outstanding question about this over in https://github.com/phetsims/ratio-and-proportion/issues/205#issuecomment-729318851. I will combine that with this issue here.

**Comment by emily-phet** [comment]
I've not worked on finalizing pointer areas in a sim in modern times...
Here's a few questions:
- Does it matter that the sim screen icons have multiple overlapping pointer areas, instead of just one for the whole button image? If ultimately this doesn't matter... I guess it's fine to me, but since these are serving as a single button image it struck me as odd that the pointer area is multiple overlapping ones for the objects inside the button image. 
- On the create screen - I don't see the pointer area for the lock ratio checkbox. Functionally it covers both the checkbox and the label, which seems right to me. 
- Is it standard that the accordion box pointer area is just over the button? If this was a decision made to standardize across sims, ok, but if not, the whole heading area of the accordion box being in the pointer area would be better I think. 
- Scaling of pointer areas - as the sim gets smaller - i.e., mobile phone size, is it possible to have the pointer areas scale up? I'm guessing this might be a new thing. Primarily I'm worried about the hands, I think it would be great for the pointer area to increase more as the hands get smaller, but also slightly larger pointer areas for the buttons, combobox, etc. would probably be very helpful on smaller devices. Not sure how much additional effort this will take, if you have an estimate (or if this is not possible) let me know.

**Comment by emily-phet** [comment]
@zepumph I spoke with Amy and Amanda yesterday about my pointer area questions. The first three bullet points above are all good, I understand better now how pointer areas work and what's "typical". 

Let's not worry about scaling the pointer area extra for small screen sizes. We've already done a lot more optimizations than normal for sim to address mobile phone scenarios - so let's just role with what we've got.

**Comment by zepumph** [comment]
Sounds good. I also don't see any possibility for hand pointer area overlap in master right now. Closing
