### ISSUE TITLE
Challenge 3 in the Discover section makes the "in ratio" sound when both at tick 1

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/ratio-and-proportion#297]
**Test device**
Lenovo

**Operating System**
Win 10

**Browser**
Chrome

**Problem description**
This is for https://github.com/phetsims/QA/issues/582
For Challenge 3, as you move the hands further and further down using the "Both hands" feature in keyboard nav, the sim acts as if the hands are getting closer and closer to the correct ratio. Once you reach the 1 ticks, the sim makes the "in ratio" sound, even though this is not the intended ratio. 

**Steps to reproduce**
1. Go to "Discover" section
2. Click on the drop-down to challenge 3
3. Use keyboard navigation, click Tab until the Both Hands feature
4. Click numbers from 9 to 0 and observe. 

**Visuals**
![ratiodiscover1](https://user-images.githubusercontent.com/72031637/102253794-a486bf00-3ebc-11eb-9d0e-95e7a66ad059.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.77/phet/ratio-and-proportion_all_phet.html
Version: 1.0.0-dev.77 2020-12-08 00:32:10 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by zepumph** [comment]
The reason for this bug is that when both hands are set from 2 to 1, the model thinks that the sim is "moving in direction", which get's a lower fitness threshold to play the in-proportion sound. 

I think that this is similar to the need for smoothing in https://github.com/phetsims/ratio-and-proportion/issues/299#issuecomment-745597310, and I will try to think of these together for now.

**Comment by zepumph** [comment]
The above commit really was for https://github.com/phetsims/ratio-and-proportion/issues/299, but I linked to here too, because the above case played the "moving in proportion" sound in addition to the "in proportion" sound.

As for the in-proportion sound, I was able to expand the same sort of logic to the model proper, as well as to the in-proportion sound. I also factored out the method into a Model function, which felt nicer to me than duplication. @brooklynlash can you please confirm this is fixed, and feel free to close.

**Comment by brooklynlash** [comment]
This seems fixed on Win10 Chrome, no "in proportion" sound at the 1 tick. Closing
