### ISSUE TITLE
Icons appear to be individually pickable

### ISSUE THREAD

**Issue by jbphet** [phetsims/ratio-and-proportion#303]
While working through the code review in #286, I noticed that the icons for the home screen and nav bar seem to have individually pickable components.  I'm not sure why this is, but I don't think I've seen it in any other sims, and would suggest making the individual sub-elements unpickable for simplicity.

Here are a couple of screenshots made during the `showPointerAreas` testing that illustrate:

![image](https://user-images.githubusercontent.com/3082831/102280283-175a5f00-3eea-11eb-95e5-acb38e2eeffa.png)

![image](https://user-images.githubusercontent.com/3082831/102280318-28a36b80-3eea-11eb-95b8-8dbd7c063292.png)

**Comment by zepumph** [comment]
This is because the icons use Nodes that are interactive. Even unpickable elements will show their pointer areas with that query parameter. For example, if a parent Node is pickable:false the child will still render their pointer areas.

The left icon (two hands) uses icon creation that already sets pickable false: https://github.com/phetsims/ratio-and-proportion/blob/29577f8befa6e4f58e8a362e13092ebf02d3c67b/js/common/view/RatioHandNode.js#L200.

The NumberPicker's icon creation could use a similar line, added above!

Although the above commit is good for completeness, I don't think it changed the behavior at all. This is just a weird case where the pointer areas are shown, even under/as unpickable Nodes.

Anything else here?

**Comment by jbphet** [comment]
Okay, sounds good.  I didn't realize that unpickable nodes still show point areas.  Closing.
