### ISSUE TITLE
Investigating scaffolding issues - Remote Interviews

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#31]
I'd like to see how far along we are - with the support of only a few prompts (i.e., Can you find multiple places where the screen turns green? and Can you keep the screen green?) - in supporting learners to do the following:
- move both on-screen hands
- find a green screen
- find multiple green screens
- recognize that they can "find green" continuously from low on the screen to high on the screen (enacting this continuously if using a touch screen device, enacting this piecemeal if they're not)
- using the grid and numbered grid to describe the proportion, and specific ratios.
- "Challenge" options being explored, but not too early, and in ways that allow for application of learning happening during sim use rather than making initial explorations overly complex.

To do this, we'll need sim prototypes just for interviews that:
1) Remove grid scaling radio buttons (2a:2b, 3a:3b, etc.) *and* options for onscreen cursor (hand, circle, cross). So, no grid scaling buttons (a:b only), or cursor options (on-screen hands only).
2) Have ratio selection options in a drop down box
3) Has no sound on or available

Once we have this @BLFiedler please use this version for 2-3 remote interviews with college students, and place de-identified clips in a shared folder.

**Comment by BLFiedler** [comment]
@zepumph  Emily & I talked about the simplified version for user testing

- Display only 3 options for the grid and only use the horizontal grid:
1. None
2. Grid
3. Numbered Grid

Something like this:
![image](https://user-images.githubusercontent.com/47331395/80520418-a3f9e200-8946-11ea-8d6a-78b25e2ff471.png)

**Comment by zepumph** [comment]
After discussing with @emily-phet, we will move everything else to the options dialog. This way it will be less confusing as to the difference between "design option" controls vs actual UI for the sim.

**Comment by zepumph** [comment]
Alright, all UI not specified above has been moved into the options dialog. I refactored a lot of the underlying Properties that control this into something called "designingProperties" with the thought that they are more temporary, and are just being used to inform the design process.

Let me know if you want any more tweaks for the sim before interviews. 

I will note that the only feature that has been lost from the sim entirely from the refactor are the vertical lines. Since they weren't desired for the interviews, and the code was not easy to just add a radio button to the options dialog, I kept it out. Once there is a better idea how we want them to be integrated into the UI, a refactor will be in order for the underlying Properties, but until then I felt like it was cheaper to leave it out.

I'm also defaulting to no grid, is that desired?

The current challenges are 1/2, 1/3, and 1/8. Would you like others?
@BLFiedler over to you.

**Comment by zepumph** [comment]
Here is a dev version https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.14/phet/ratio-and-proportion_en_phet.html

One other thought, "Grid" is a bit of a misnomer, since it is just horizontal lines. 

There are a lot of thoughts above, feel free to split them out into side issues, especially if they are to be done after interviews.

**Comment by BLFiedler** [comment]
@zepumph @emily-phet

I discovered the following while playing around with dev.14, and I think we should sort this out before going to interviews:
![image](https://user-images.githubusercontent.com/47331395/80610660-d95e0880-89f6-11ea-899f-fd189d1b7b11.png)

I tried to put the hands at around 3 & 6, but did not get success feedback for doing so. I moved the right hand around until I found it, which from the perspective of the grid does not match a 1:2 ratio. Perhaps this is related to #36 ? or the discussion in #5 ?

**Comment by zepumph** [comment]
After discussion with @emily-phet and @BLFiedler, we fixed the above label bug, and also toggled visibility of the black rectangles when units are displayed. 

Here are the new dev versions:
without sound: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.15/phet/ratio-and-proportion_en_phet.html?sound=disabled

with sound: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.15/phet/ratio-and-proportion_en_phet.html

**Comment by BLFiedler** [comment]
After experimenting with dev.15 on an iPad, it does require Chrome for the audio to work (as a note for future interviews). Safari does not work.

**Comment by BLFiedler** [comment]
For dev.15, cue arrows not present during touchscreen use (requires hover).  Noticed during interview with user on iPad & Safari. 

@emily-phet , do we want to reconsider the "hover" requirement? They will never see the cue arrows if using a touchscreen. I wonder if the presence of cue arrows might help cue the learner to pick up both objects at the same time.

**Comment by emily-phet** [comment]
Indicated in separate issue to do related to marker cueing arrows. 

Sim version and dev link needed for this round of interviews was created and used. Closing issue.
