### ISSUE TITLE
(mobile a11y) - Accordion box not opening or closing on iOS 14.2

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#316]
When testing [dev version 78](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.78/phet/ratio-and-proportion_en_phet.html) on: 
-  iPhone 8 with iOS 13.5.1
-  iPhone7 with iOS 14.2

I found that the Accordion box worked fine on iOS 13.5.1, I could not open and close the My Challenge Accordion box on iOS 14.2.

Tagging [QA issue 582](https://github.com/phetsims/QA/issues/582)

**Comment by terracoda** [comment]
This issue might be related to https://github.com/phetsims/scenery/issues/1094

**Comment by zepumph** [comment]
Yes it is exactly that @terracoda, because of the problem with iOS 14 outlined in https://github.com/phetsims/scenery/issues/1094, the accordion box is being clicked twice, so it is toggling open and then closed again. Unassigning and marking on hold until that issue is complete so that we can double check then.

**Comment by terracoda** [comment]
Using ios on iPhone7 14.3, I can now open and close the accordion box with and without iOS VoiceOver enabled.

I am not sure the fix for phetsims/scenery#1094 has been applied or if it was my iOS update to 14.3, though I assume the ix has been applied as we discussed it last week.

**Comment by terracoda** [comment]
Last comment is no longer true as of this morning.

**Comment by zepumph** [comment]
This is fixed from changes in https://github.com/phetsims/scenery/issues/1094
