### ISSUE TITLE
Rewrite fitness algorithm

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#325]
From code review by @jbphet over in #286, he had some ideas about how the fitness algorithm could potentially be simpler and better. 

Basically the current function takes inputs of x/y (left/right hand positions) and the target ratio to discover how far away from the ratio the current values are. It does this by treating one of the positions as "correct", and then maps the other to how far away it is from the ideal. To explain it in terms of the picture below, the algorithm calculates the distance by the min distance in cardinal directions when plotting one of the two points that intersect `y=leftPosition` and `x=rightPosition`. 

![rap-graph](https://user-images.githubusercontent.com/6856943/103037691-ec3ec380-4518-11eb-8200-b826aa3155ed.png)

@jbphet's idea is to treat the target ratio as a function (like the red line above), and to calculate the cartesian distance between the point of the current ratio (x,y), and the closest point on the function. That is represented by the perpendicular orange line, where the current position is somewhere on that.

It would be simple enough to create the function from the target ratio, since the positions are normalized between 0 and 1. And I think it could be pretty straight forward to calculate the inverse/intersecting function that intersects perpendicularly with the target ratio function while intersecting the current position.

As an MVP, I think we could rewrite the guts of the fitness algorithm, but keep the output Properties as a test. This way we could experiment with the feasibility of this without rewriting any/much view code.

I don't think this is my top priority, but I also don't feel like it would take too long to discover if this was worth doing before initial publication.

Tagging previous fitness algorithm work done in https://github.com/phetsims/ratio-and-proportion/issues/14

**Comment by zepumph** [comment]
Just to reiterate, this would be a large model change, and it is quite late in the process, but I don't think this would necessarily take the large number of hours that the title of this issue seems to hint at.  My estimate right now would be 3-4 hours.

**Comment by zepumph** [comment]
I ended up just committing directly to master, because the behavior seemed to be the exact same as on master. This algorithm feels much simpler to me. Thanks @jbphet, I really appreciate your help. Could you please review this new fitness algorithm, so see if it was what you were thinking?

**Comment by jbphet** [comment]
> Could you please review this new fitness algorithm, so see if it was what you were thinking?

Yes, this was pretty much what I had in mind, and I'm glad you've found it useful.  The only other thing that I was thinking was that there would be an explicit "distanceFromTargetRatioProperty" in lieu of "unclampledFitnessProperty", since that's a little easier to understand, and `getMinFitness` would then become `getMaxDistance`, and `calculateFitness` would be `calculateDistance`, and the last line of `calculateFitness` - the one that converts the distance into a fitness value - would only exist in the calculation for `ratioFitnessProperty`.  My thinking here is that most everything is then about a distance calculation, and thus pretty explicit and mathematical, and the interpretation of that distance into a 'fitness' value occurs in only one very localized place.

You (@zepumph) know the sim far better than I, so it's up to you to determine whether this makes sense and, if so, whether it's worth doing.

A couple of other minor things.  One is that I found this `if` clause in `RAPModel` a bit confusing:
```
      if ( this.inProportion( unclampedFitness ) &&

           // If either value is small enough, then we don't allow an "in proportion" fitness level, so make it just below
           // that threshold.
           ( this.valuesTooSmallForInProportion() ||

             // In this case, the normal model behavior looks buggy because both values are equal, but still in proportion.
             this.ratioEvenButNotAtTarget() ) ) {
```

One of the cases that it seems like it is testing for is one in which `this.inProportion( unclampedFitness )` and `this.valuesTooSmallForInProportion()` to both be true, but their names seem to imply that they wouldn't be true at the same time.  If the logic is indeed correct, perhaps some renaming would help.

Finally, I made a couple of very minor changes to a comment that I think had some typos. Please verify that my changes were correct.

**Comment by zepumph** [comment]
That makes sense. Thanks for the clarity. I do agree that using distance as an unbounded metric, and fitness from 0 to 1, will clean everything up nicely. I'm not sure if time will allow for this before first publication. I'll take a look.

**Comment by zepumph** [comment]
After looking into this further, I don't think I want to factor things out into a distanceProperty, because that distance depends on the target ratio. I wouldn't want spots that need to look at that distance have to normalize on target-ratio, which is basically what the "unclamped" fitness is doing currently. Perhaps if we were still designing description, I would test out what it sounded like for the ratio proximity regions to just use the distance, but my guess is that altering the region ranges based on the target ratio would not be acceptable anyways. With this in mind, I'm ready to close this. Thanks for all the help @jbphet.
