### ISSUE TITLE
Remove RAPRatio.antecedentProperty and RAPRatio.concequentProperty from model

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#327]
From https://github.com/phetsims/ratio-and-proportion/issues/286, it is confusing to have these, and a tupleProperty. Ideally everything would be based on the single tupleProperty setting.

**Comment by zepumph** [comment]
These would then move to the elements in the view that require them, and would try to force everything else that doesn't NEED them (i.e. because they aren't common code built around a single NumberProperty), to use the tupleProperty instead.

**Comment by zepumph** [comment]
I was able to remove all of the easy usages above. Basically these are all vestigial from before there was a tuple. To me they seem much cleaner using the tupleProperty like this. Now there are two more places that use the individual values, and I'm unsure if we will be able to factor them out.

1. In RatioHalf.js. Since RatioHandNode (sub component) is an AccessibleValueHandler, to support individual slider interaction, we need a `NumberProperty` for each ratio term to be able to pass into that. 
2. This is related, but we actually require the exact same reference to the individual term Properties to be in HandPositionsDescriber.getSingleHandDistance to be able to get a term-specific description (left hand/right hand). This is pretty fragile, and so I should probably fix this anyways. 

RE (1), note that in RatioHalf, we already create a DynamicProperty that maps the individual to a 2D one to support the DragListener. Perhaps we can do the same thing there for the individual one too. First I will need to break the link in (2) above. Then this should likely be easy.

**Comment by zepumph** [comment]
Wow. I'm really happy with https://github.com/phetsims/ratio-and-proportion/commit/86c9350df178f6f7e18b068603424494ba940605, and this issue's refactoring in general. I think I'll keep going on (2) above, and try to create them directly in RatioHalf.js.

**Comment by zepumph** [comment]
Now there is only a `tupleProperty` in `RAPRatio`. @jbphet does this make more sense to you? Now RatioHalf creates two dynamicProperties to take the model (which only has a tuple of two terms) and map into a single number (for keyboard interaction via RatioHandNode's AccessibleValueHandle), and into a 2d position for the DragListener in RatioHalf.

I agreed heavily with your sentiment during code review that it was confusing to have both. How does it look to only have a tupleProperty now?

**Comment by zepumph** [comment]
a couple small bug fixes. The infinite loop was happening because of how DynamicProperty used comparison to determine if listeners should be called. In general using deep equality is cleaner in this case.

**Comment by jbphet** [comment]
For future reference, the comment in the parent issue where the cost/benefit for the tuple approach versus separate properties is discussed is https://github.com/phetsims/ratio-and-proportion/issues/286#issuecomment-751870514.

**Comment by jbphet** [comment]
Above, @zepumph asked:

> @jbphet does this make more sense to you?

Absolutely, I think this is a very positive step that will make the code easier to understand and maintain.

I have two follow-up suggestions, and one is only partly related, so feel free to break it into a separate issue if desired.
- I think it would be helpful to explain why a tuple is used in `RAPRatio` instead of individual properties, using some of the information from https://github.com/phetsims/ratio-and-proportion/issues/286#issuecomment-751870514.
- The documentation for `changeInAntecedentProperty` and `changeInConsequentProperty` says, "the velocity of each ratio value changing, adjusted in step".  The name would suggest (at least to me) that these represent the amount of change that occurred on the most recent update of the tuple, but the documentation seems to say that it is an amount of change over time.  I would suggest changing the names or the documentation - or both, if necessary - to make it more clear what these values represent.

It's okay with me to close this issue once these suggestions have been considered and addressed.

**Comment by zepumph** [comment]
Sounds great thanks. I don't think this work should block publication.
