### ISSUE TITLE
Lock Ratio correction out of order

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#342]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/601. Documented with log querry parameter.
It is possible to achieve at ratio, but be slightly off. When clicking the Lock Ratio box, the hands are meant to slightly jump to be exactly in ratio. According to @zepumph this is meant to happen when you check the box. Instead, it happens when you begin to move the locked hands.

**Visuals**
![OoOoflockratio](https://user-images.githubusercontent.com/41024075/106823987-1bc80c00-663f-11eb-9cee-519265df0a25.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-rc.1/phet/ratio-and-proportion_all_phet.html?log
Version: 1.0.0-rc.1 2021-01-26 23:41:16 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
Language: en-US
Window: 1280x687
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by KatieWoe** [comment]
Interesting note: If one of the hands is at the top and would need to shift up to reach ratio, the clicking the lock ratio button seems to immediately jump the other hand in to position without needing to move the hands.

**Comment by zepumph** [comment]
I thought that this would have been happening already, because of this line, but it seems like something is wrong with it, and it only works after you move the ratio when  its locked

https://github.com/phetsims/ratio-and-proportion/blob/002a0538253a9f6e64318faf18f20b98756c2e29/js/common/model/RAPModel.js#L103

**Comment by zepumph** [comment]
This bug was from this line, where I take the current RAPRatioTuple and then mutate it. Instead I should create a new one. I found it a bit easier to just keep the antecedent and consequent values separate. Committed above. 

I also fixed a logic error where I wasn't snapping the smaller of the two values, like I said I was in doc and design decision, so I flipped an inequality sign. 

@KatieWoe can you please confirm fixed on master.

**Comment by KatieWoe** [comment]
Looks ok on master.

**Comment by zepumph** [comment]
cherry picked to branch

**Comment by KatieWoe** [comment]
This looks good in rc.2
