### ISSUE TITLE
Inconsistencies about requirements to hide interactions cues

### ISSUE THREAD

**Issue by phet-steele** [phetsims/ratio-and-proportion#365]
I am somewhat confused! It looks like there are three "states" for these interaction cues:

(1) The individual movement Up/Down arrow keys
(2) The simultaneous movement W/S arrow keys
(3) The simultaneous movement Up/Down arrow keys

What I notice is that you clear the cue for (1) by pressing Up/Down while having focus on just one hand, which is great! This keeps the cues for (2) and (3) when you tab to simulatneous focus, which is also great! Then you have to press W/S to get rid of (2), while still keeping (3) visible, then you have to press Up/Down to get rid of (3). That's all great!

However, my confusion stems from the idea that clearing (1) first does not clear (2) or (3), BUT clearing (2) and (3) first does clear (1)?

The sensical steps:

1. Enter a screen
2. Tab until you are controlling just one hand
3. Press Up/Down to clear (1)
4. Tab to go to simultaneous hand control, and notice the cues for (2) and (3) are still there. That makes sense to me.

The confusing steps:

1. Enter a screen
2. Tab until you are controlling both hands
3. Press W/S to clear (2)
4. Press Up/Down to clear (3)
5. Shift-Tab to go back to single hand control, but notice the cues for (1) are gone? Why?

I am seeing this behaviour on Win 10 Chrome. For phetsims/QA/issues/617

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-rc.3/phet/ratio-and-proportion_all_phet.html
Version: 1.0.0-rc.3 2021-03-03 03:29:06 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
Language: en-US
Window: 1920x937
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
</details>

**Comment by phet-steele** [comment]
Originally reported by me at https://github.com/phetsims/ratio-and-proportion/issues/350#issuecomment-790159673.

**Comment by zepumph** [comment]
Individual hands are a completely different interaction than both hands. Up to lead designer @BLFiedler to determine if this warrants further action. Feel free to close if we aren't going to change this.

**Comment by terracoda** [comment]
From a visual keyboard user's perspective, I agree it may seem illogical that all the Arrow key cues disappear when both the left and right hands of the Both Hands interaction is used first. The Both Hands interaction, however, is a complicated custom interaction. When keyboard users are successful with the Both Hands interaction, it should be safe to assume that using the individual Left and Right Hands should be a walk in the park. Using the Up/Down Arrow keys is the natural intuitive first move.

The Both Hands keyboard interaction, however, needs to be cued in unison, so that's why first using the individual Left or Right Hands does not clear the visual cues for the Both Hands interaction.

The goal is to remove the visual cues (which are very strong, especially when you include the big fat grey arrows that are visible on page load) as quickly as possible, without jeopardizing the visual cues for the custom Both Hands interaction.

I'll just add, from a non-visual perspective the visual cues are not an issue. The individual Left and Right Hands are clearly communicated as sliders to people using screen reader software. The Both Hands (custom) interaction is communicated as "Both Hands, movable" and includes permanent help text available in the PDOM.

And, if a learner only uses mouse or touch, the Up/Down Arrow keys and W/S keys never come into play, so again, not an issue for this group.

I hope that helps. I personally, am comfortable with the behaviour as-is.

**Comment by terracoda** [comment]
I agree that the steps suggested by @phet-steele https://github.com/phetsims/ratio-and-proportion/issues/365#issue-821617892 are indeed logical, but it means we could be strongly cuing an intuitive move longer without really needing to.
