### ISSUE TITLE
If ratio is high enough, it may be impossible to hit with a mouse

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#369]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/617.
If the ratio is large enough, such as 1:10, then it may be impossible to hit the in ratio with a mouse with lines turned off. The sound will play, but you will always be going past it and the checkbox does not activate.

**Visuals**
![rangetoosmall](https://user-images.githubusercontent.com/41024075/110701559-89230b80-81ae-11eb-82fe-d15f67433872.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-rc.3/phet/ratio-and-proportion_all_phet.html
Version: 1.0.0-rc.3 2021-03-03 03:29:06 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0
Language: en-US
Window: 1280x687
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</deatils>

**Comment by KatieWoe** [comment]
Incredibly strange addition. If you get it in ratio using the lines, then turn lines off, you can get it in ratio with the mouse.
![doesnow](https://user-images.githubusercontent.com/41024075/110702143-5fb6af80-81af-11eb-800f-0f076d032923.gif)

**Comment by KatieWoe** [comment]
Seen with 1:7, 1:8, 1:9, and 1:10

**Comment by zepumph** [comment]
Yes it is a bummer that mice aren't quite granular enough to lock in a small ratio like this. Note that you can actually zoom into the smaller hand and get more granularity that way. 

Everything else you mentioned here is an intentional design choice. We purposefully play a sound when passing over the proportion because that sound represents "entering in-proportion state" and so conceptually passing through in-proportion involves entering and exiting.

We are most likely not going to change anything here. @BLFiedler, @terracoda @emily-phet please reopen if you feel differently.

**Comment by zepumph** [comment]
@KatieWoe talked me through this in a zoom call, and there does seem to be a particular bug in regards to not being able to hit exactly 1:10 when the challenge is 1:10. We can't reproduce with any other place but when the right hand is at 10. We could reproduce together at challenge ratio of 1:8, and sometimes at 1:9, though I couldn't get it at 1:7 at all.

**Comment by zepumph** [comment]
@jonathanolson and I discussed this, and really it boiled down to a general usability/accessibility problem for mouse users. We are pretty confident that the reason for strange/different results in the above bug report and what I can reproduce is simply based on the resolution of the screen and the scale of the sim/layoutBounds when you are attempting to reproduce this. Since the left tolerance range when at 1:10 is so small, it comes down to individual pixels, and the granularity that they can give to the model. 

@jonathanolson and I decided to try to work in a minimum position/pixel/distance value such that when less than that, you will have the in-proportion state. It may be challenging to balance having this work well on all screens, and not get too gross in the view (looking at pixel values).

**Comment by zepumph** [comment]
I do not think this can actually be in the model, because on larger resolution displays (that we may not be able to test on), we don't want to pigeon whole minor changes into a hard coded granularity snapping. Instead I really feel like it has to be based on pixels.

**Comment by zepumph** [comment]
A hard coded minimum distance is working nicely on my screen:

```diff

Index: js/common/model/RAPModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/RAPModel.js b/js/common/model/RAPModel.js
--- a/js/common/model/RAPModel.js	(revision c130db19bd30e55c34185015692d18ef6564ac06)
+++ b/js/common/model/RAPModel.js	(date 1615842043508)
@@ -148,6 +148,15 @@
       targetRatio = 1 / targetRatio;
     }
 
+    const idealAntecedent = consequent * targetRatio;
+    const idealConsequent = antecedent / targetRatio;
+
+    const minimumDistanceToProportion = 0.0005;
+    if ( Math.abs( antecedent - idealAntecedent ) < minimumDistanceToProportion ||
+         Math.abs( consequent - idealConsequent ) < minimumDistanceToProportion ) {
+      return 1;
+    }
+
     // Calculate the inverse slope from the current target ratio.
     const coefficient = -1 / targetRatio;
 

```

The only trouble is trying to fine-tune the distance for all devices:

* 0.0005 works to fix this bug reported in this issue for 1:10, but not 1:8. This is while I am fullscreen.
* 0.001 works to fix 1:10 and 1:8 at full screen for me. 
* 0.005 seems too big, and can take away from staccato range in smaller threshold spaces. 

This strategy in general may be a bit flawed if we always want to allow the in-proportion state, no matter the screen size. I cannot get in-proportion given an arbitrarily small size, but I sorta feel like it is morth work than it is worth to pursue looking at the view pixels to determine these differences.

I would be most included to commit .001 to code, but marking for design meeting tomorrow.

**Comment by zepumph** [comment]
We confirmed that .001 and this algorithm in general is the way to do. 


>This strategy in general may be a bit flawed if we always want to allow the in-proportion state, no matter the screen size. I cannot get in-proportion given an arbitrarily small size, but I sorta feel like it is more work than it is worth to pursue looking at the view pixels to determine these differences.

We don't feel too worried about incredibly small/weird screen sizes, but do want to test on a few typical devices. 


I will commit code like that above patch, and toss it to @BLFiedler to review. Then QA should likely take a look on most of our weird resolution devices.

**Comment by zepumph** [comment]
Applied above with a value of .001.

@BLFiedler please take a look on master or with https://phet-dev.colorado.edu/html/ratio-and-proportion/1.1.0-dev.6/phet/ratio-and-proportion_all_phet.html

**Comment by terracoda** [comment]
I am going to comment, but I have a feeling we can't fix this, when I explore My Challenge with 1:10 with keyboard I can't get ratio with Left Hand at 0.1 and Right Hand at 1. All other spots starting from Left Hand 0.2 are good.

However, if I just click on the Left Hand when it is at 0.1 and Right hand is at 1, the sim goes into proportion/ratio.

Here's 0.1 with keyboard
![Screen Shot 2021-03-17 at 12 10 33 PM](https://user-images.githubusercontent.com/1902116/111485903-fb996b80-8719-11eb-9fea-5fa50c182a54.png)

**Here's after I click with mouse. The mouse click doesn't visibly move the Hand, but there is a change - maybe a slight snapping?**
![Screen Shot 2021-03-17 at 12 11 06 PM](https://user-images.githubusercontent.com/1902116/111486919-da854a80-871a-11eb-988a-07de422c885e.png)

**No problems at 0.2 which is very good**
![Screen Shot 2021-03-17 at 12 02 32 PM](https://user-images.githubusercontent.com/1902116/111485350-7f9f2380-8719-11eb-9c34-4d9687e71e5e.png)

I can move into 0.1 with the mouse and get the chime. I just cannot do it with the keyboard shift key. I can at 0.2:2, though, so that's good!

**Comment by BLFiedler** [comment]
For the purposes of the first three challenges on screen 1, I think these changes are fine.

re: @terracoda 's comment. Is the 0.01 in the hollywood region? Should the snap-to keyboard feature be able to capture the L0.01-R0.10 values for target = 0.1?

**Comment by terracoda** [comment]
re: @BLFiedler question, "Is the 0.01 in the hollywood region?", I am not sure what was decided on that, maybe we set that to 0.2? @zepumph, do you know? Did I find a bug or a design decision?

**Comment by zepumph** [comment]
RE @terracoda's comment, I think it is a bit of a bug, when the hollywood was adjusted in https://github.com/phetsims/ratio-and-proportion/issues/83#issuecomment-658303665 (the commit right below), the hollywood was made to include "`.1` of a tick mark", but perhaps it would be better as an exclusive relationship. 

![image](https://user-images.githubusercontent.com/6856943/111718074-29f87300-880e-11eb-8316-c9ea61199301.png)



I committed a fix that yields that above screen shot. I'll cherry pick to a branch and proceed with the next RC. Thanks for the bug report @terracoda.

**Comment by zepumph** [comment]
cherry picked to 1.0

**Comment by KatieWoe** [comment]
This looks good in rc.4
