### ISSUE TITLE
Context responses need updating for single hands

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#419]
From #413.

- [x] For all position landmarks and distance landmarks and at ratio, we should never hear distance progress response (just distance region).

**Comment by terracoda** [comment]
As mentioned in meeting, the context responses that are currently firing for the indy hand sliders is not working properly. I went a tested the Interactive Description for the same version and that is also not working, but in the exact opposite way. In both cases I hear the appropriate object responses, but not the appropriate context responses:
- For Voicing: The only context responses I hear are the ones that contain the distance-progress strings.
- For Interactive Description: The only context responses I hear contain the distance-region strings.

FYI, I also tested the published sim's Interactive Description, and while the two different context responses are firing there is a least 1 bug and some room for improvement. The bug us sometimes and I can figure out when, I hear hear the incorrect distance-progress string (I will create a separate issue for this if one doesn't already exist). 

In terms of clarifying the improvements we need, I am thinking it through, and will comment again asap. The previous comment (https://github.com/phetsims/ratio-and-proportion/issues/419#issue-1103933693) is indeed one idea that I think would make the experience better.

**Comment by zepumph** [comment]
Above I commented out the description context response so that you can test what is currently implemented. It was a little different from what we discussed on friday. When in the same distance-region,  it will alternate between that distance region and the distance progress region:

```
Very close to right hand, in lower region.
Closer to right hand, in lower region.
Very close to right hand, in lower region.
Closer to right hand, in lower region.
Very close to right hand, in lower region.
Closer to right hand, in lower region.
Very close to right hand, in lower region.
Closer to right hand, in lower region.
```


Just so you can know. This most likely shouldn't change how we are going to proceed with voicing.

**Comment by terracoda** [comment]
As I mentioned in today's meeting this alternating logic should gracefully handl single-value regions like:
- "at top"
- "at middle"
- "at bottom"
And then we will hopefully only have one edge case - "hands at challenge ratio". I think pedagogically it is better to distance region rather than distance progress when  learner hits the challenge. I think they need to connect the approximate distance between the hands, their positions and the being at the challenge ratio. The distance-progress string is not the information they need when they reach the challenge.

**Comment by zepumph** [comment]
All the distance regions were covered by the bug fix in https://github.com/phetsims/ratio-and-proportion/issues/416. Above I made sure that in-proportion will never have distance progress either. Please review, does all look right to you @terracoda?

**Comment by terracoda** [comment]
@zepumph, I think we are onto something good here, but we have lost "position-region" for mouse exploration. It's so hard to tell which string is what since they all three are so qualitative, so I am going to repeat it here. We have three possible dynamic strings in context responses:
1. **distance-region**: the strings that describe the range is distance between the hands. The distance parameters go from "farthest from" to "even with" 
2. **distance-progress**: just 2 parameters here -"Closer to" and "Farther from"
3. **position-region**: the qualitative position of the hand in the vertical space of the Play Area (or the tick mark position when tick marks are selected). The no-tick-mark position strings range from "at bottom" to "at top". 

Ignoring the fact that some of the position-regions are single value landmarks (at top, at middle, at bottom), we originally had 2 possible arrangements for context responses:
A. a context responses composed with strings 1 + 3, or
B. a context response composed with strings 2 + 3.

**Note** that this is still true for keyboard exploration.

**Pedagogical Needs**
The **position-region** is definitely required on end drag because it helps learners compare that when the hands are in the lower part of the vertical space the hands will need to be closer together to be at ratio (or in proportion), and when the hands are further up the vertical space they will need to be farther apart when ratio (or proportion) is found.

**Design Questions** 
1. Do we need position-region during active drag with mouse and touch in Voicing? I am not 100% sure on this.
2. Do we need position-region at end of drag? Yes, we definitely need it here.

**Next Steps:**
Can you add the position-region strings back in for end drag only for mouse/touch? Is that possible? If so, I can try it out, and hear what that is like? If it's easier to add position-region back in for both active dragging and end drag, we can also just try that route.

**Bugs**
I want to note that sometimes I hear "no right hand" or "no left hand". I think this happened to close to the top and then again close to the bottom. I have isolated it yet.

**Possible General Improvements**
Just noting that at the end of drag, i.e., the release of a hand, the interruption sometimes is less than ideal. This also happens in GFLB, so any improvement or solution here will be a general one. No action required at this time, just something to think about, in general for Voicing and sliders.

**Comment by terracoda** [comment]
@zepumph, can you comment on or work on my suggestions for **Next Steps** (above)? Once we get that sorted, we can work on narrowing down the **Bug** that I mentioned.

**Comment by zepumph** [comment]
Ugg, yes, I'm so sorry that I ditched the position regions, my mistake. I guess my mind was way too involved on the distance side of things. You can test above. The bug and potential improvement have been moved to separate issues.

**Comment by zepumph** [comment]
@terracoda, at this time, I believe that the keyboard interaction (voicing and description) is also ready for review.

**Comment by terracoda** [comment]
There are more bugs visual and and text related:
- visual arrow key icons do not go away when using keyboard
- aria-valuetext is not updating for keyboard. E.g., one hand can be read out as hands at challenge ratio and when focus moves to the other hand the hands are far from challenge ratio (no movement of hands).

But on the positive side, I think the distance-region and distance-progress parameters are implemented correctly. I have only tried no tick marks and default key presses.

**Comment by terracoda** [comment]
Need to narrow down when I hear "no left hand" or "no right hand".

**Comment by terracoda** [comment]
@zepumph, I think the context responses sound really good in interactive description. I tried 3 different voice rates:
- my usual Voice rate: 55
- slower than usual voice rate: 40 I'll try some slower and faster voice rates to double check.

**Comment by terracoda** [comment]
It might sound different in other screen readers, but I think we can leave timing tweaks alone for now.
