### ISSUE TITLE
Hands snapping to "around" Nth tick rather than "on" Nth tick mark

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#421]
This might already be on our radar as something we would address with the Voicing design, but just in case I am making an issue so we make sure we fix this for Interactive Description, too.

When using VoiceOver and a mouse in published version, I could see some very slight snapping to the tick mark line, but VoiceOver would always say "around Nth tick mark" rather than "on Nth tick mark".

I know we don't expect VoiceOver users to use the mouse, but they can, and if there is snapping behaviour, the description should also snap to that same described value.

This is important for alignment with the Voicing design. We will need/want to hear "on Nth tick mark", and not "around Nth tick mark" when a mouse user lets go of the hand near a tick mark and it snaps to the tick mark.

**Comment by terracoda** [comment]
@zepumph, we can address this as we work on implementation of the indy hand sliders issues #413 through #420.

**Comment by terracoda** [comment]
The snapping and the snapped-to description work fine when tick marks are enabled. The issue I described in #420 is happening because there is no snapping and "At middle" is a super tiny region - hard to hit with  mouse input.

**Comment by terracoda** [comment]
Actually, I can get the incorrect description during active drag. The correct snapped-to description only happens at end of drag.

**Comment by zepumph** [comment]
Ok, I see, 3 issues here, and I discussed them with @terracoda.

1. General snapping of keyboard, rounds to a step of .06 in certain cases (the unit test in https://github.com/phetsims/ratio-and-proportion/commit/7a344388346ae7a7c25d156944d2ee8210435f66). @terracoda and I decided that this is not a bug. The primary design goals are to (a) make sure that you can get in-proportion for every target ratio, and (b) snap to the "grid" that is the keyboard step you are using (making sure that if you use a mouse, then keyboard steps again, it rounds to the half-tick-mark). I'll revert the commit.
2. Description region vs in-proportion tolerance inconsistency with mouse when you haven't let go. This seems similar to https://github.com/phetsims/ratio-and-proportion/issues/437, where we have inconsistent/unhelpful responses until we let go (end drag) because there isn't snapping until you let go. Likely we won't solve this in RAP, but it is important to name. I'll create an issue. 
3. Bug where VO would say around when you were on while using a mouse + VO (so mouse with description?). This seems to be what @terracoda was reporting in https://github.com/phetsims/ratio-and-proportion/issues/421#issue-1110870296. We will make this issue devoted to that bug. Over to @terracoda to see if she can reproduce this.

**Comment by terracoda** [comment]
Now (on PhET test on March 2) when using VoiceOver and a mouse on MacOS 11.4, I hear object responses (descriptions about proximity to ratio) when actively dragging, and I only hear context responses - responses that contain distance-region & position-region (tick-mark-region) - at end of dragging (letting go). 

This is not an issue on master, and I also checked VoiceOver on the published version, and the context response only fires at end of drag, so not a problem there either.

Item 2, above remains an issue when Voicing is being used. And we may have (unfortunately) more than the edge case described #437 

Closing this issue with VoiceOver since it is not actually happening - with VoiceOver, I get the correct region in the response at end of drag as the mouse snaps to the region.
