### ISSUE TITLE
sometimes I hear "no right hand" or "no left hand"

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#423]
From https://github.com/phetsims/ratio-and-proportion/issues/419, @terracoda said:

>I want to note that sometimes I hear "no right hand" or "no left hand". I think this happened to close to the top and then again close to the bottom. I have isolated it yet.

I'll investigate

**Comment by terracoda** [comment]
@zepumph, I think I am hearing "no right hand" or "no left hand" when I am within the tolerance to be in ratio, but not exactly at ratio.

**To reproduce:**
1. Using the keyboard, move a hand so hands are at challenge ratio.
2. Then using the mouse, move a hand just a tiny bit, but not so much that the screen changes color.
3. You should hear "no right hand" in the context responses when making that tiny movement with the left, or "no left hand" when making a tiny movement with the right hand.

I tell ya, these tolerances are finicky things.

Is there a fix for this situation for Interactive Description? If there is just apply the same fix to Voicing.
There might not be a fix yet as most of interactive description focuses on keyboard/focus input rather than mouse input.

So, I'm thinking if the hands are at challenge ratio and a hand moves a little, but does not move enough to be out of the tolerance range that determines being at the challenge ratio, then the other hand should still be at the same distance or same position as before.

**Comment by zepumph** [comment]
Ahhh, very good! Thanks for the report, you are actually hearing ` null left hand`. Here are some examples using `?printVoicingResponses`:

```
hands, at challenge ratio, null left hand, on fourth tick mark.
hands, at challenge ratio, null left hand, almost on fourth tick mark.

```


Investigating now.
