### ISSUE TITLE
New feature for pointer/focus interaction for continuous ratio exploration

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#43]
I was thinking more about the unifocal interaction configuration (pointer, keyboard/switch focus) and how to lift the obstacle of continuous ratio exploration that is possible with bimanual exploration.

I'll preface this by saying I'm not sure this should be on by default, but may be considered a "pointer/single-focus" mode or similar idea that is accessible in the PhET menu (like an enhanced sound feature).

When this mode is enabled, a new, focusable UI element appears to the left or right of the cursor play area in line with the Left cursor. I've imagined a vertically oriented double-headed arrow. When selected and dragged up or down, the Left and Right cursors are smoothly translated up or down according to the ratio defined by their CURRENT POSITION. i.e. the left cursor will translate 1:1 with the double-headed arrow, and the right arrow will move in a multiplicative fashion. For example, if the Left cursor is at a value of 1 and the Right cursor is at a value of 1.9, then the Right marker will move at a rate of 1.9 times that of the left (1.9/1) to maintain the proportion set by the user.

This way, the user will be able to continuously explore the proportion they set and IF that proportion matches the challenge proportion (e.g. 1:2), then it will maintain the success feedback as it is moved. i.e. if they are on a ratio of 1:2 and move the double-headed arrow, it will STAY GREEN, play the success sound, provide the success haptic feedback, etc.

If they are not in the perfect proportion, they will never see the success feedback by using this UI element, but they will receive the out-of-proportion feedback across modalities.

Ideally, this leverages the existing sound design and visual design.

For the sound design, the already explored "moving in green" success sound will play just like it would during moving in green with bimanual input.

Description may need to be modified to indicate movement of multiple objects and corresponding proportion feedback?

I'd be interested in your thoughts @emily-phet and @Matthew-Moore240 

Bad mockup:
![image](https://user-images.githubusercontent.com/47331395/81321958-7b619e80-9050-11ea-852c-29982d255b37.png)

Translation upward:
![image](https://user-images.githubusercontent.com/47331395/81322355-18bcd280-9051-11ea-807e-c5537c4f5d4e.png)

**Comment by emily-phet** [comment]
@BLFiedler Thanks for this idea!

The central challenge of supporting single focus movement (a binary operation) of the two hands lies in the fact that maintaining ratio during continuous motion requires two actions 1) changing y (height of hands) and changing delta (distance between hands) - it's hard to control both in a single keypress. You're idea is a nice way of collapsing this into a logical two-step operation, setup starting scenario and then in a single press raise the hands. 

This approach assumes, though, that the learner either already understands the mapping (and expects that the hands will raise at different rates corresponding to the ratio, or that there task should become figuring out what this feature is (continuous movement at the preset ratio). 

Another (less efficient) approach would be to have a focus feature that highlights both hands, so a single keypress moves them both up...but keeps their current delta. Since in all the setups, the right hand needs to be higher than the left, the most efficient process would be to alternate between moving both up, and then moving the right one up. It's not continuous, but may be more aligned with helping learners figuring out what the delta means. Does that make sense. 

Not saying this is a good idea, but just trying to think through through different approaches, and how they relate to supporting learners in developing an understanding versus doing the action efficiently.

**Comment by emily-phet** [comment]
Another thought here - the original proposed idea would involve minimal effort (single keypress) to maintain success once success was reached. 
We ultimately want a way to require *effort* in maintaining green - we don't want that effort to be too complex, but *more* should have to be done actively by the learner to maintain success, rather than less.

**Comment by emily-phet** [comment]
Enacting some approaches to solve the challenge brought up here over in #62.
