### ISSUE TITLE
Update voicing position regions

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#433]
From https://github.com/phetsims/ratio-and-proportion/issues/363

https://docs.google.com/document/d/1offJbONUg8y5Aa9kHewC9iTDtNISzna4giGt7WrpXCk/edit#heading=h.jthi63tcg8wx

**Comment by terracoda** [comment]
Copying an image of the table here from the design document - for the record:

**Because we came up with new pointer-input logic for distance-progress** information while implementing the Indy Hands (No Tick Marks), **we may not need to simplify the position region names**. Ideally we want these region names to be the same across Interactive Description and Voicing.

![image](https://user-images.githubusercontent.com/1902116/155777722-7dffea93-ac31-444d-9ba4-3cc460c8db1e.png)

**Comment by zepumph** [comment]
Let me know when/if you would like something implemented.

**Comment by terracoda** [comment]
We are not taking the path to rename regions, so I am going to close this issue. We can open this issue in the future if we find a need to re-design any described regions (voicing and interactive descriptions). Ideally, scaffolding this complicated should remain the same for both experiences.
