### ISSUE TITLE
Update tick mark position regions for voicing

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#434]
From https://github.com/phetsims/ratio-and-proportion/issues/363, see 

https://docs.google.com/document/d/1offJbONUg8y5Aa9kHewC9iTDtNISzna4giGt7WrpXCk/edit#heading=h.hf7fzk15hsv9

**Comment by terracoda** [comment]
@zepumph and @terracoda discussed the edge-case when using a mouse there is no snapping to the "At middle" region which is a single-value region. It is difficult to land on that region when using a mouse, but when the Right Hand is "At top", the tolerance for the ratio makes it easy to find the challenge ratio within a range of space around the "At middle" region.

But hearing "In lower-middle region" or "In upper-middle region" and "At top" might not lead to making sens of ratio 1:2.

We are going to test two tiny regions--"Around middle"-- on either side of the "At middle" region, to if that sounds better. 

In response land, instead of hearing the wider position region name a learner will hear:
"hands, at challenge ratio. Not so close to right hand, around middle"

And, of course, they might still have a chance of landing on "At middle". The three regions together should be wider than the ratio tolerance, so if the left hand is "In lower-middle region" or "In upper-middle region" and the right hand is "At top" the hands will not be at the challenge ratio.

Over to you @zepumph.

**Comment by terracoda** [comment]
@zepumph, wrong issue! Deleting and creating new issue.

**Comment by terracoda** [comment]
Copying two tables from the design doc here so I can record the design. I will review the documentation of the hand interactions before we make any major changes to regions. Hopefully, we can leverage distance-progress with Tick Marks, as we did with No Tick Marks.

![image](https://user-images.githubusercontent.com/1902116/155782651-962f2d26-82f7-462b-8c68-45c4dc7626df.png)

![image](https://user-images.githubusercontent.com/1902116/155783062-e4a01ad8-a216-4d3a-af5f-c668e4f0b3f5.png)

**Comment by zepumph** [comment]
>I will review the documentation of the hand interactions before we make any major changes to regions. 

Sounds like we are still in design mode.
