### ISSUE TITLE
Need name response on Range Combobox

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#445]
I think implementation is missing a name response, but I am double checking. Will report back asap.

**Comment by terracoda** [comment]
Yes, we have an object response instead the combined name response when the combobox is opened with pointer input.

And the text for the hint needs to be a customized one, different from PDOM.

Upon opening the range combobox with a click or tap, with hints checked, I should hear:
- Range: 0 to 10, Choose range for tick marks.

And the same hint for the other inputs.

Everything else is good.

**Comment by zepumph** [comment]
We will want to talk about this. It is quite hard to do this, but I'd like to explain this more. I believe we discussed this a bit in https://github.com/phetsims/sun/issues/726.

**Comment by terracoda** [comment]
Ok, we can discuss at today's meeting. The weirdest part for me, is that there is no Name Response at all when no checkboxes are checked in Preferences, and "Range: 0 to 10" is text on the screen.

I am just copying in current design to document it:
![image](https://user-images.githubusercontent.com/1902116/159014023-3a2acc2c-b77a-4047-9fa8-ca0447adbe1a.png)
![image](https://user-images.githubusercontent.com/1902116/159014101-b3334c47-bb9b-4743-9e60-2d31616f0db8.png)
![image](https://user-images.githubusercontent.com/1902116/159014171-af4562b5-2902-4c0d-9841-07d02d0abc99.png)

**Comment by zepumph** [comment]
@terracoda and I talked through this problem today. The main issue is that when you select the button, you are actually getting the voicing because the list item Node is focused, thus, to add this, we would also need to say the name response when cycling through options. This is not ideal.

@terracoda thinks this may be acceptable, because you still get the name response upon selection, but will want to discuss with @emily-phet.


>The weirdest part for me, is that there is no Name Response at all when no checkboxes are checked in Preferences, and "Range: 0 to 10" is text on the screen.

You will still hear "Range: 0 to 10" upon selection (even if the selection didn't change), you just don't hear it when you open the combo box with a mouse/touch.

Over to @terracoda to see if there is anything else here.

**Comment by zepumph** [comment]
@terracoda! I think I can make this happen easily afterall!!

@jessegreenberg and I discussed, I can adapt `supplyHintResponseOnNextFocus` to handle the case where we supply the nameResponse instead of the hint response. Assigning back to me.

**Comment by terracoda** [comment]
That would be ideal, especially for Sims that have really meaningful comboboxes like Molarity.

**Comment by zepumph** [comment]
Ok. @terracoda please review master now. I think it is you desire with the name response on open. Commits in https://github.com/phetsims/sun/issues/726
