### ISSUE TITLE
Need additional context response when number spinners unlock the Ratio Lock

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#447]
Is it possible to have an additional context response when interaction with the number spinners unlock the Ratio Lock?

This response is part of Interactive Description, but I think it might have been difficult to implement.

In Interactive Description these two context responses fire in quick succession:
- Hands no longer locked.
- Current challenge 1 to 3. Hands, far from new challenge ratio.

Can we add "Hands no longer locked." to the string of responses in Voicing?
- 3, Hands no longer locked. Current challenge 1 to 3, Hands far from new challenge ratio.

**Comment by zepumph** [comment]
Right! Thanks for the reminder and ping. We have this in the description, I just didn't do this yet in voicing.

**Comment by zepumph** [comment]
Looks like both are there: https://github.com/phetsims/ratio-and-proportion/blob/1ccb1e3afa8ffe9f82d1d0d8e649cdb6a3889bed/js/common/view/BothHandsPDOMNode.ts#L186-L190. My guess is that this isn't coming through because of Utterance settings (like cancelSelf). I'll just combine the utterance instead.

**Comment by zepumph** [comment]
It is indeed all about timing and interrupting. Just like for description, order matters. Unlike in description, voicing is set to interrupt each other, so it isn't just about order, but making sure that both come through. Because of this, in the case where you change the number pickers, the "Hands no longer locked" response must come after the original context response. This isn't the case for the both-hands when pressing a number to unlock the ratio. 

@terracoda please review, and confirm that the description still sounds alright also.

**Comment by terracoda** [comment]
Ok, I hear the order like this:
- object response = new value of number spinner = "3"
- context response with _appended lock response_= "Current challenge 1 to 3, Hands far from new challenge ratio. **_Hands no longer locked._**"

From what you said above, I think you **cannot** pre-append the lock response to the front of the context response, so it would be like this:
- object response = new value of number spinner = "3"
- context response with _prepended lock response_ = "**_Hands no longer locked._** Current challenge 1 to 3, Hands far from new challenge ratio."

Is that the case? You cannot pre-pend the lock response to the context response?

**Comment by zepumph** [comment]
Yes. This is because they are not technically one whole response, but two responses, and that means two utterances. The context response like "Current challenge 1 to 3, Hands far from new challenge ratio." is controlled by common code and cannot be easily (or perhaps at all) told to not interrupt the other separate response that says "Hands no longer locked." I'm sorry for the trouble.

**Comment by terracoda** [comment]
Hmm, ok, let's not spend anymore time on this right now, assuming there is no way to set a priority level and have the "Hands no longer locked." response fire first as soon as the model knows the hands are no longer locked.

**Comment by zepumph** [comment]
Sounds good. Yeah it is a bummer that the ordering is seemly so closely tied but actually they are coming from far, far away.  Would you like to close this issue?

**Comment by terracoda** [comment]
@zepumph, will investigate a little bit more.

**Comment by zepumph** [comment]
Ahha! Priority is working really well here. I can't remember why I thought that announcer options was the only tool here for ordering. @terracoda have a listen. Anything else here?

**Comment by terracoda** [comment]
This is sounding great. Closing.
