### ISSUE TITLE
Both-hands context response good when using individual hand with ratio locked - move edge response to start of drag

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#452]
Related to https://github.com/phetsims/ratio-and-proportion/issues/451. When we reach the edge, with ratio locked and controlling an indy hand, we don't get the "Both hands" context response.

Current description:

>hands, at challenge ratio, Left Hand, near bottom. Move hands up to explore more.

What we want to see:

>hands, at challenge ratio, Hands almost even with each other, both hands near bottom. Move hands up to explore more.

**Comment by zepumph** [comment]
The issue is the same as #416, but now we need two instances of BothHandsDescriber, one for voicing and one for description, otherwise the context response that is requested second (voicing in this case) will be as if it is the second context response at the edge (our criteria for a "go beyond" alert.

**Comment by zepumph** [comment]
@terracoda please review the hand voicing bugs we created together 2 weeks ago.

**Comment by terracoda** [comment]
The context responses at the edge - the ones that communicates the edge has been hit and that the learner should change directions (move down to explore more or move up to explore more) is working perfectly when I have focus on either of the individual hand sliders and with any one of the explore modes slected (No Tick Marks, Tick Marks, Numbered Tick Marks).

The context responses are not yet fixed if my focus is on the Both Hands interaction. 

Perhaps this is because we have not yet implemented the Both Hands interaction? Not sure. I find this strange because with the Ratio Lock in locked position, all the responses should be the same regardless of which actual interaction has focus. 

I will change the label to question, and leave the issue open for @zepumph to comment. 
**Question:** Should Both Hands already be fixed, or will it be fixed when Both Hands are fully implemented?

**Comment by zepumph** [comment]
@terracoda explained this further to me, the keyboard + indy hand + ratio locked is working well, but two other modalities are not:
* Mouse + ratio locked, we go from this response to this response:
`hands, at challenge ratio, Hands not so close to each other, left in lower-middle region, right near top.`
`hands, at challenge ratio, Right Hand, at top. Move hands down to explore more.`

We should get a position response with "at top" before the hint "Move hands down. . . ."

* Keyboard + both hands + ratio locked. Same issue as originally reported above. We get the "move hands down" upon first arrival at the edge.
* keyboard + Both hands + ratio not locked (and indy hands non locked): Here aren't getting any "move hands down". It looks like go beyond alerts were only implemented for the both hands interaction. @terracoda will make another issue for this, perhaps it was purposeful, and perhaps it was just an oversight.

**Comment by terracoda** [comment]
@zepumph, for mouse/touch input (pointer input), the timing it too finicky to provide a hint about changing directions at End of Drag. The natural place for this kind of hint is at start of drag when there is no value change at all and only if one hand is at the edge. This should work well for keyboard input, too, when the Ratio Lock is checked. 

Does this approach make sense to you? More specifically:

When Ratio Lock is checked and a hand is at an edge position (at top or near bottom) we adjust the wording of the hint response. So that at start of drag the hint helps indicate the best direction, rather than trying to guide a change in direction at the end of a drag. If this makes sense, we won't have a hint at end of drag when the Ratio Lock is checked.

This should work perfectly for pointer input, and I think it should work just fine for keyboard input. 

**Special wording for Hint Response when starting at an edge & Ratio Lock is checked:**  
- Right Hand, at top. Move hands down to explore more.
- Left Hand, near bottom. Move hands up to explore more.

Should this be a separate issue? It seem related to this issue.
