### ISSUE TITLE
User Experience wierdness when Ratio Lock is checked

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#456]
In #452 I think we decided to have a consistent name response of "Both Hands" for the Voiced experience when the Ratio Lock is locked (checked).

However, a learner can still put their keyboard focus on an individual slider when the ratio is locked. Once the visual hints go away, the interaction sounds the same, "Both Hands".

I may have asked this before and was told that it is not possible, so if that is the case, that's ok. 

Would it be possible (when ratio is locked) to may the indy sliders work with W and S keys just like the but not actually provide a visual hint for that? I don't want the hints to change.

<img width="873" alt="image" src="https://user-images.githubusercontent.com/1902116/161579453-95060d26-5b51-4d29-91bd-1fb7830758f4.png">

<img width="872" alt="image" src="https://user-images.githubusercontent.com/1902116/161581515-58388a87-fd37-4588-80cc-18a9c17cd60b.png">

**Comment by zepumph** [comment]
We could add an option like "alternativeIncrementKeys" and "alternativeDecrementKeys", and check them here:

https://github.com/phetsims/sun/blob/571e04d1cd9417929e753c68a2048a5d76dcd0b7/js/accessibility/AccessibleValueHandler.ts#L624-L629

We could not easily mutate this list dynamically, at least without being tricky. I would like to discuss this with @jessegreenberg just to see if he sees an easier way to handle this.

**Comment by jessegreenberg** [comment]
Agreed @zepumph, that seems like how we would do it! Do we know if we get input events from letter keys for an `<input type=range>` for each of VoiceOver, NVDA, and JAWS? I suspect we do but that might be the limiting factor.

Otherwise, maybe we replace `<input type=range>` with `<div role=application>` and use KeyboardDragListener?

**Comment by jessegreenberg** [comment]
If we don't want to add options to AccessibleValueHandler, maybe a sim-specific listener for these letter keys would be better. That might actually be harder to implement. I am not too worried about adding options like this to AccessibleValueHandler.

**Comment by zepumph** [comment]
@terracoda and I discussed this today, we don't want to devote resources to this now, since we are quite sure that @jessegreenberg is right and that role "range" will block W and S keys while a screen reader is on. We feel like there is a good chance that in the future we may still want this feature even if it only works with Voicing, especially since there are cueing hints that mark the left hand with W and S in the both hands view. It would be easy to learn via that modality, and then be confused when going back to the individual left hand. For now we will mark as deferred and unassign. Mostly just keeping open to note the design consideration.

**Comment by zepumph** [comment]
This issue has a better solution over in https://github.com/phetsims/ratio-and-proportion/issues/415!! There we decided to change the name response of the individual hands to "Both Hands, Locked". Closing
