### ISSUE TITLE
Media Pipe does not seem to work in the Safari

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#472]
Related to #454, on Mac OS 12.2.1 using Safari, I can't seen to get media pipe to work.
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/1902116/171045564-d25d5185-2ec9-45e3-99b1-1d5df18ba051.png">

I was advised to use Chrome which works well, but am opening this issue in case we need to investigate why it is not working in Safari.

**Comment by zepumph** [comment]
@emily-phet: "I think this is worth a quick search to see if there is an obvious reason/fix for this."

If it involves more development to work around this, then let's hold off.

**Comment by zepumph** [comment]
@marlitas (who has a mac and safari) and I have investigated this extensively today. We discovered a couple of things. 

1. The mediaPipe hands demo worked for @marlitas. https://code.mediapipe.dev/codepen/hands
2. We found that safari by default disables the ability to use media devices (video/audio) from untrustworthy sources. This means localhost! Turn it on with https://stackoverflow.com/questions/44523609/getusermedia-is-not-allowed-in-localhost-safari-11
3. @marlitas didn't have much luck in PhET even after this because she uses a non-default webcam device, and safari wasn't really picking it up automatically for her. Boo safari
4. We found a great hello world for piping a webcam stream into a video element and used this to make sure this was safari's fault, and not PhET's code. It is safari's fault! https://www.kirupa.com/html5/accessing_your_webcam_in_html5.htm
5. We adapted that using this demo https://github.com/webrtc/samples/blob/gh-pages/src/content/devices/input-output/js/main.js to allow for switching between devices, and it is working quite well! Even on safari.

Thus, we think that the next step is to add the ability to change devices in the mediaPipe options, see https://github.com/phetsims/ratio-and-proportion/issues/494.

On hold until we get done over there.

**Comment by zepumph** [comment]
@terracoda was just reviewing this and found that we had to follow step (2) before safari allowed this to work on on phettest (bayes.colorado.edu). She will report back if this setting was also needed for accessing a dev version on phet-dev:

https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.29/phet/ratio-and-proportion_all_phet.html?cameraInput=hands&showVideo

**Comment by terracoda** [comment]
This dev link is working fine in Safari with the new Input Device set-up.
https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.29/phet/ratio-and-proportion_all_phet.html?cameraInput=hands&showVideo

Note that one does have to Allow the video camera in Safari's preferences and may even have to do this repeated every time you reload or clear the cache.

**Comment by terracoda** [comment]
And Camera Input: Hands is also working fine on master with Safari.

**Comment by terracoda** [comment]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/1902116/184985780-c9b2c2da-c841-4ef5-b289-1999aa8630cd.png">
