### ISSUE TITLE
Empty Node in SimControlsNode adds extra separator to "General" tab

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/ratio-and-proportion#497]
Reported in https://github.com/phetsims/joist/issues/814#issuecomment-1221091478

The empty content for the "General" tab adds the separator like this
![image](https://user-images.githubusercontent.com/6396244/185708409-63e0bf7c-aab3-462c-9f50-f42ba6674860.png)

Would it be OK to conditionally provide sim controls behind MediaPipeQueryParameters.cameraInput instead of the current default which adds an empty Node?

**Comment by zepumph** [comment]
Yes indeed! I'm doing that now in RAPPreferencesModel since https://github.com/phetsims/ratio-and-proportion/commit/36135be4eb90bf99da8f6b16d5be7231e0535b5f.

Note though that this is in the input tab, so there isn't worry of an extra separator line, but instead the whole input tab being present and blank. Closing
