### ISSUE TITLE
Camera Input is basically unusable on iPad

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#513]
**Test device**
iPad 6th Gen
**Operating System**
iPadOS 15.6.1
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/qa/issues/831. When using camera input on the iPad the sim lags so badly that it is essentially unusable. In addition, the camera on the device has trouble picking up movement on top of this.

**Visuals**

https://user-images.githubusercontent.com/41024075/189718013-ed09773b-e345-4345-a3f3-0dfe80a07d9b.MOV

**Comment by zepumph** [comment]
@emily-phet is this acceptable, or should we work on iPad performance here?

**Comment by emily-phet** [comment]
I'm a bit surprised by this. It sounds like two issues - 1) performance, and 2) tracking. 
Re 1) I would have expected ok performance from a newer generation iPad, but that certainly doesn't seem to be the case. Re 2) I wonder if the challenge picking up hand motion stems from the lighting in the room - since it appears there's a bright overhead light. 

I don't think we should address performance issues at this time for iPad alone. If it's an issue across many devices, we can reconsider. Right now let's just document and include in information for teachers that there may be performance issues on iPad. 
@KatieWoe - can you do a quick check of the hand tracking capabilities in a setting with more even lighting? Nothing fancy, just something without a single bright light right in the camera view and see if that aspect seems improved or not?

**Comment by KatieWoe** [comment]
The trouble picking it up seemed to be more the size of the camera and the logistics of having it point at the user while still having free hands. The lighting didn't seem to be an issue, I was more having trouble getting both hands in screen and having room to move them.

**Comment by stemilymill** [comment]
I tested on chromebook to see if the performance is an issue. It was still laggy, but significantly better than on my ipad, and i would definitely consider it useable.

**Comment by zepumph** [comment]
I tried out this on the iPad, and it was really quite bad, https://codepen.io/mediapipe/pen/RwGWYJw. But not as horrible as phetsims. This seems to be entirely a performance issue. I know that the mediaPipe models are computationally expensive, and they need to do quite a bit of analysis on each frame's picture. 


A couple of thoughts for next time (happy friday)

* The `?profiler` wasn't working on iPad. 
* What if we just step half as much for mediaPipe in mobile a11y. Then instead of getting lagged down with more than it can handle, we can just have a bit less granularity.
* I need to go back to some other investigation with TS about how to test locally with video, because I can't get video to work from unbuilt version over http.

**Comment by zepumph** [comment]
@emily-phet and I feel that It is important to spend some time on this issue. We will check back in next week.

**Comment by zepumph** [comment]
After testing again with the above performance metrics, it is still totally horrible and unusable. I decreased the video picture by a factor of 4 (less pixels to compute), and I'm only analyzing every other frame. Still it is horrible. 

https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.33/phet/ratio-and-proportion_en_phet.html?cameraInput=hands

I will make some query parameters for easier testing on iOS and see if any values help things.

**Comment by zepumph** [comment]
I was able to get the profiler working on an iPad, I see that with this link we hover around 7-8FPS without any hands on the screen. Perhaps it is something outside the actually computation.

https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.35/phet/ratio-and-proportion_en_phet.html?cameraInput=hands&ea&cameraFrameResolution=3&cameraImageResolutionFactor=.05&profiler

**Comment by zepumph** [comment]
@emily-phet and I discussed this and decided it wasn't worth more investigation at this time. I'm going to close this issue with these weak workaround put into the sim for iOS. Closing
