### ISSUE TITLE
Should sim start in successful ratio?

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#52]
This was talked about briefly during sound meeting today with @BLFiedler, @jbphet, @Ashton-Morris, and I. We were curious, especially from a sound perspective, if the sim should start in an already successful position. 

We have not solidified a sound design yet, but we decided that we didn't like a "continuous" sound for a successful ratio. This may make the startup sound feel a bit weird. But we will need to play around with it more to know for sure.

Is it set in stone to start in proportion?

**Comment by BLFiedler** [comment]
I mentioned that this was a choice for our implicit scaffolding early on, but that the team as a whole had not discussed so the reasoning should at least be recorded here for posterity, if not discussion.

**Comment by emily-phet** [comment]
It's been my belief that the sim starting at the target ratio provides a significant benefit as it: 
1) sets up a scenario where the learner's initial interaction with the markers causes clear and obvious dynamic feedback (change in color, etc.), 
2) invites an initial question "why was it different and how to do I get it back to that", (so the learner has at least one obvious goal to work towards from the outset)
3) makes clear from the start what (at least some) of the success feedback is
4) and ensures that the learner always knows at least one place where success happens. 

Without this, the prompt of "make the screen green" or equivalents are more mysterious and arbitrary. If the sim starts at success, prompts can go ahead and start with "make the screen green in multiple places". Additionally, knowing what some of the success feedback is at the outset may become all the more important as we shift some/all feedback to only when markers are near the success ratio, as opposed to providing some specific feedback all the time. If a learner moves the markers just a tiny bit, and gets no dynamic feedback, that's really bad. Some learners are timid in the first few seconds, and the displays have to respond big to reassure the learner they're doing something meaningful, even if they're not sure what it means yet.

From a mechanistic reasoning perspective, learners need to be able to determine rapidly what are the relevant objects (markers), and relationships between the objects (initially...that's just "arrangements can cause no feedback, some feedback, or success feedback ") as quickly as possible. If we don't start at success, we are requiring that all learners go through a process of trying to figure out what success is, without having given them the hint at the outset by starting at success.

For sound, I think it's fine if there is no sound to start, and then as the learner moves the markers they will necessarily hear "near success" feedback, since any movement will be "near" success rather than "on" success. Perhaps another way to think of it is that the sound is indicating when the *learner* has positioned the markers near or at the target ratio, rather than *whenever* the markers are at or near the target ratio.

I'm happy to hear benefits to starting not at success, though. Perhaps I'm missing some and they ultimately outweigh the benefits I expect to see from starting at success. And ultimately, interviews will be the ground truth. If what we see in interviews doesn't align with what is listed above, or if we decided to explore a different starting setup for comparison, learner interactions have the final say. :)

**Comment by zepumph** [comment]
That sounds really nice! I mean to assign myself not you @emily-phet to read this. I am convinced and ready to close. Please reopen if there are other thoughts.
