### ISSUE TITLE
Ratio selection and input

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#56]
The current accordion box "Challenge" selector - used to change between different ratio settings - needs to be updated.

At its core, the solution needs to support:

- Selection of three different ratios
- Result in exploration of the first ratio first (*not* encourage flipping between ratios too soon)
- On the third challenge only, there needs to be available an option to show a pair of number spinners, allowing for selection of a custom ratio (and the ability to show/hide the input). 

One thought for how to do this is to have a "My Challenge" collapsible box appear (collapsed) once the third challenge is selected. Expanding this box shows a pair of number spinners (or pickers, I can't ever keep these straight), allowing input of the ratio values.

**Comment by emily-phet** [comment]
@BLFiedler Can you take a stab at designing this? I suggest talking to @arouinfar and asking for her thoughts, based on her experience across sims.

**Comment by arouinfar** [comment]
I'd be happy to talk about this with @BLFiedler, but I am completely unfamiliar with this sim (aside from MK's status updates) and would need to know more about the context. I believe @amanda-phet is on the design team, so she may have some good insights here.

**Comment by BLFiedler** [comment]
Aggregating ideas here for discussion: https://docs.google.com/presentation/d/1N-9y7mmTNV0nTIVuXPW_cvawPb9frY2-GWdxTraS8kc/edit?usp=sharing

**Comment by BLFiedler** [comment]
Okay - have some ideas put together with some additional ideas and refinement from @arouinfar !

### Challenge Selection (1-3)
- I believe this is still best accomplished with a combobox (dropdown), as it keeps the other challenges out of view, while highlighting the challenge you are currently on.  It has an implicit hierarchy from top-to-bottom that guides users to do them in order (which we have seen users do in interviews, i.e. we have not seen them do them out of order). 

- One possible change to consider is a language change in the dropdown box to help imply that the challenges increase in difficulty from top to bottom is, while maintaining a label that says "My Challenges", refer to each of the challenges by Level. While a little more "gamey", I think Level here implies more "Level of Difficulty" than "Game Level":

![image](https://user-images.githubusercontent.com/47331395/83191523-63ca8280-a0f1-11ea-977b-2d4a9824397c.png)

- Otherwise, we could consider some other "rating" system like 1,2 or 3 stars to indicate the level of difficulty of the Challenge. However, I think this would require an unnecessary increase in description as compared to "Level". 

### Custom Ratio
The challenge here is to decide when and how the user reaches and sees the custom ratio. 
- The constant I think is how the ratio is chosen once they do see it. I think the best choice might be a number picker side-by-side for the Left and Right hands (similar to Proportion Playground or Gravity Force Lab Basics), so it is clear you are chosing the number corresponding to each side, but not necessarily letting on that you are choosing a ratio/proportion (should they stumble on this before they have figured out the idea of the sim) This is in constrast to say, a fractional representation:
![image](https://user-images.githubusercontent.com/47331395/83192516-e6077680-a0f2-11ea-8da9-d1716852590d.png)

Next is under what circumstances they see the accordion box, a few options in order of I think increasing complexity, as well as railroading for the user:
1. If using the Level language, we make Level 4 the Custom ratio with the accordion box already open and set to some value (1:1? or the least selected challenge?). By placing it as the last "Level", it is likely they will not choose it until last. The caveat here is if someone thinks they "get it" and want to jump right to the hardest difficulty, they will encounter this custom scenario instead which may be confusing:
![image](https://user-images.githubusercontent.com/47331395/83193146-cc1a6380-a0f3-11ea-8647-2a453751a03b.png)

2. The Custom ratio exists on a new Screen which we could call "Custom Challenge", "Mystery", or Lab" maybe. Users typically proceed from left to right when exploring PhET sims and wil llikely not move onto screen 2 (the custom) until they've finished with screen 1. The custom screen opens looking much like screen 1, but with the accordion box present with the number pickers inside. It would start open, but could be closed so that one student or teacher could, for example, set a challenge up, close the accordion box, and hand the sim over to another student/learner to figure out.

3. Conditional appearance of Custom Challenge: 
The Custom Challenge accordion box appears on the same screen as Challenge 3 when Challenge 3 is selected from the combo box. 
- This could be done so that it appears in a corner with the accordion box closed when Challenge 3 is selected **OR**
- The appearance of the Custom Challenge accordion box could be conditional based on some metric like: distance hands have traveled, time, or something else that indicates the user has spent some amount of effort trying to figure out Challenge 3 before they are presented with the Custom Challenge.

**BF Thoughts:**
Personally, if we are open to another screen, I think option 2 offers the best balance between dissuading users from jumping right to the Custom Challenge when they first encounter the sim, but not forcing them into a particular interaction to access it if they want to experiment more with the sim, show someone something (e.g. hopping between challenges and return to custom), or come back to the sim later to jump right to playing with the custom scenario. Option 3 requires them _learn_ what they have to do to trigger the custom scenario and takes several more steps, making it less attractive to return to later. I think Option 3 is worst for that. So I'd go 2 > 1 > 3.

**Comment by emily-phet** [comment]
Thanks @BLFiedler:
What if we did this:
- Keep accordion box as is (labels staying the same: "Challenge 1", "Challenge 2", "Challenge 3", etc. 
- There's a collapsed panel below the accordion box labeled "My Challenge" (there's some weirdness here, since the accordion box opens down, but if we like this idea we can sort it out). The collapsed panel is not active (you can't open it) until you have found a new "success" point in (all, some, Challenge 3?) challenges. This is indicated by the collapsed box being grey in color and maybe having a "lock" image on it. Once it's unlocked, it becomes active, and learners can open it to expose the number picker setup @BLFiedler [has above](https://github.com/phetsims/ratio-and-proportion/issues/56#issuecomment-635609441). 
It's a bit game-y, but perhaps not overly so.

Some resulting issues:
- does the accordion box open over the collapsible panel, or push it down?
- what is the criteria needed to unlock the collapsible panel
- what does the accordion box say when the number pickers are available - since none of those challenges are active.

**Another variant (I like this one - I believe it's a slight tweak to @BLFiedler number 1 above):**
- Keep accordion box as is, but add to "Challenge 1", Challenge 2, Challenge 3 a "My Challenge" option. When "My challenge" is selected, the number pickers appear, inside of a collapsible box. 
- Maybe the number pickers are not active until all of the other challenges are interacted with. If that's the case, then they'd have to have a greyed out "null" design when not active. Also, the makers would have no area that turns green (or maybe they become inactive with a big 'lock' graphic when "My challenge" is not active.
- Or we just let "My Challenge" be available all the time and accept that some kids will use it early, and be ok with that. 

**Regarding a second screen**
- There's a ton of associated overhead for having a second screen, so if there's no other functionality beyond having a "My Challenge" option, we shouldn't go this route.

**Comment by emily-phet** [comment]
@BLFiedler - Let's talk about this during Tuesday's RaP design meeting.

**Comment by emily-phet** [comment]
Thinking about this more - there is an added benefit to having the "my challenge" option be on the second screen. We don't necessarily need the grid number changes available on the first screen for the preset challenges - 0-10 work just fine. A second screen would allow us to put both the "my challenge" option and the grid number changes on a second screen...which still wouldn't be enough to make me think "second screen needed" typically...but since we care a lot about the exact sequence of interaction for a wide range of research purposes for what's happening in the current "Challenge 1, 2, 3" paradigm, moving everything else to a second screen may make sense here.

Let's go with a second screen, and ask @zepumph to build it. 

@BLFiedler Please sketch on paper a second screen (doesn't have to pretty, just clear). Play area as it is in the first screen, grid control as it is described in #55 (three horizontal buttons), and instead of the "Challenges" accordion box, a collapsible "My Challenge" box, open on startup. Below that, an accordion box with "0-10, 0-20, and 0-30" options (like in [this comment](https://github.com/phetsims/ratio-and-proportion/issues/36#issuecomment-623666589) in issue #36).

Since the "My Challenge" box will be open on startup, I think it will nicely disambiguate the two screens for those flipping between them.

**Comment by BLFiedler** [comment]
Done below. Hopefully what you intended. It felt a little strange to separate the scale from the grid controls, so I moved them below, but above the challenge box. I assume the scale dropdown will only appear when the numbered grid option is selected? I'm happy to quickly redraw if you think the scale combobox should go below the My Challenge accordion box.

Again, I really like the idea of separating the custom from the other three challenges (be it by another screen or another option) just to allow some "replayability" and "sharability". I could definitely see a teacher opting to create something custom, closing the challenge box, and having a student try to figure it out. Or students challenging each other! This would just be rather frustrating if you had to go through a series of steps to access it. **However, this is all secondary to the primary experience sequence of going through the preset challenges,** so I see how careful we need to be to make sure this is not something people navigate to immediately for the first-time experience.

![image](https://user-images.githubusercontent.com/47331395/83423837-c6b96380-a3e8-11ea-8104-168350b4a6db.png)

**Comment by emily-phet** [comment]
@BLFiedler Looks great (hands and all!). 

@zepumph we may end up wanting the radio buttons (none, grid, numbered grid), and the accordion box (0-10, 0-20, 0-30) placed **under** the "My Challenge" collapsible box...so if it's helpful, you might want to be anticipating that possible change.

**Comment by emily-phet** [comment]
Closing this - can re-open if we find significant design issues with what is planned in #58.
