### ISSUE TITLE
Additions to alternative input - number keys and jump key

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#62]
To the existing alternative input mode where both hands can be controlled simultaneously (W/S and arrow keys), please add the ability for:

- [x] Number keys (0-9) to jump both hands to that number gridline
- [x] “j” key to jumps both hands to lowest currently occupied position

This would be the same for both screens. 

Noting here - we will also need to confirm that this interaction technically works well with screen readers we support (presumably so, in role=application mode), if some sort of button "pickup" is needed to make use more intuitive for non-visual experience, and design visual cues to indicate available actions upon initial (or all) first encounter. 

Also - it was brought up last week that the number 0 could jump hands to 0 or to 10, let's start with it jumping hands to 0 position (or lowest position). Also, gridlines position can change in the second screen, for right now let's focus only on providing access to the 0-9 grid positions with the number keys.

**Comment by zepumph** [comment]
When the base unit changes for the grid, do you want the behavior of the number keys to change? It would be easiest if the numbers were treated more like percents, where `1` went to 10% of the ratio height. Do you instead want to always align these numbers to the grid number?

**Comment by zepumph** [comment]
@emily-phet and I talked today, and we do want the numbers to map to the visual grid line numbers, not to percent.

**Comment by zepumph** [comment]
Implemented above. @emily-phet please review.

**Comment by emily-phet** [comment]
@zepumph The basic behavior looks great to me. 
It seems a bit buggy though:

- I had a few times where the sound kept playing after I had moved the hands.
- The hands don't always look visually aligned. For example, on startup, go straight to using the number keys to jump the hands. They seem a bit off in horizontal placement.

Also - let's have the orange cueing arrows disappear if you use any of the keypresses to move the hands (up/down arrow keys, W/S, number keys, or j key).

**Comment by zepumph** [comment]
>I had a few times where the sound kept playing after I had moved the hands.

Right now, we only have a rough way of triggering sound to play with alternative input. The sound plays when there is focus on either hand, or on the composite ratio. You won't get any sound when fitness is 0, but you will get sound otherwise. It would most likely be good to open a  new issue to discuss this further if the current way isn't right.

>The hands don't always look visually aligned. For example, on startup, go straight to using the number keys to jump the hands. They seem a bit off in horizontal placement.

They seem aligned to me. I think there is a bit of a optical illusion when in the middle of the space with no grid lines, and I feel like they are off, but then I show the grid lines and they are right on. I wonder if what you are witnessing is #53. To check this see if the bottom "framing" rectangles are aligned, if they are offset, then refresh the sim. Sorry I haven't gotten to that just yet.

**Comment by zepumph** [comment]
I have sometimes gotten a reentrant error when pressing the 0 key. It is a bit hard to reproduce, but I think I will want to investigate. Reopening.

**Comment by zepumph** [comment]
Fixed above. Closing
