### ISSUE TITLE
Changes to layout on mobile?

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#79]
Noticed that in portrait mode on mobile, controls can look funky (too wide). Can we consider a different layout, perhaps with radio buttons vertical rather than horizontal, etc.?

**Comment by emily-phet** [comment]
@BLFiedler - assigning to you in case you have suggestions on this. If not, no problem

@zepumph - can we do this? So below a certain width the controls change such that at minimum the radio button group is arranged vertically rather than horizontally? Not sure if there is anything else that can be done to narrow the other controls...not sure we want to go down this path, but just for interests sake, can the text labels be changed on the fly for a situation like narrow width?

**Comment by BLFiedler** [comment]
I'm not sure I see this. Everything looks pretty small on my end (Chrome, Android)

![image](https://user-images.githubusercontent.com/47331395/86548966-76f41d80-befb-11ea-9a27-174cf68dc85b.png)

**Comment by emily-phet** [comment]
I think I was just being unclear above. Essentially, the controls do not seem to be our usual "big and friendly" style on mobile, so I'm hoping we can have them adjust for smaller screen sizes. 
One thought I had to do that (re-phrasing the same ideas from above), is to have the grid view buttons align vertically rather than horizontal, and to abbreviate the text in the comboboxes so that they can appear larger in size (e.g., font + padding) while taking up the same amount of space.

**Comment by zepumph** [comment]
I think the easiest thing to do would be to create a layout that works well in all aspect ratios. I'm sure you have already thought about that, but I do feel like there is a ton of vertical space in a normal aspect ratio currently. Maybe we could try to layout the grid buttons vertically always, and then things will be better on all devices.

**Comment by zepumph** [comment]
I see the difference between tall screens though, since the vertical scaling is potentially only half of the screen or so. We can also go down a more manual approach that involves re laying out the UI controls, likely by scaling them up as much as the horizontal space allows. Here is a sketch of what that may look like for tall layout:

![image](https://user-images.githubusercontent.com/6856943/88112297-0b958700-cb5c-11ea-92fb-21bf1e9a720e.png)


And then the same scaling for wide layout:

![image](https://user-images.githubusercontent.com/6856943/88112331-1fd98400-cb5c-11ea-8517-915268675351.png)


 And how I made this:
```diff
Index: js/common/view/RatioAndProportionScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/RatioAndProportionScreenView.js	(revision a3980ae1d355e7971f7f4bc14f80bbb349a6093e)
+++ js/common/view/RatioAndProportionScreenView.js	(date 1595369425087)
@@ -259,6 +259,14 @@
       this.leftRatioHalf.bottom = this.rightRatioHalf.bottom = this.layoutBounds.bottom;
 
       labelsNode.bottom = this.layoutBounds.bottom - RatioHalf.FRAMING_RECTANGLE_HEIGHT + labelsNode.labelHeight / 2;
+
+      if ( newRatioHalfBounds.height === MAX_RATIO_HEIGHT ) {
+        const radioButtonBottom = this.gridViewRadioButtonGroup.bottom;
+        this.gridViewRadioButtonGroup.setScaleMagnitude( 1.6 );
+        this.gridViewRadioButtonGroup.bottom = radioButtonBottom;
+        this.gridViewRadioButtonGroup.right = resetAllButton.right;
+      }
+
     };
     this.layoutRatioAndProportionScreeView( defaultRatioHalfBounds );
   }

```

Maybe we need a more thorough discuss about this.


I also want to note that there seems to be precedent for not scaling controls larger, for example projectile motion using custom layout to float the controls out to yield the largest projectile launching space possible. Still it relies on the layout bounds height for its scaling. Notice the reset all button's side here:

**Comment by emily-phet** [comment]
Give that this sim is actually will be best used for many in the vertical orientation, (while in projectile motion I think it's only a subset of situations benefit from the vertical orientation), I'd like to make sure the controls are at least a little better than currently in the vertical orientation. Right now it's nearly impossible to select different ranges on the second screen, for example. 
![iPhone-vertical](https://user-images.githubusercontent.com/5109055/88481151-a8ff0b00-cf0e-11ea-9311-619421d3acaa.jpeg)


Here's a screenshot of the sim vertical on my iPhone (the small size iPhone 8). I think if we could just access that buffer space (circled) and have the current layout scale up to take up that space, the controls would be large enough to be manageable for most. 

Is this a possibility? If so, is this a possible simplest way forward?

**Comment by zepumph** [comment]
I want to work on #53 before tackling this, because that bug's fix may effect the layout code that changes here. Marking on-hold until then.

**Comment by zepumph** [comment]
https://github.com/phetsims/ratio-and-proportion/issues/53 is now complete.

**Comment by zepumph** [comment]
I added scaling in the above commit. It will scale more and more depending on how much more tall the screen is than the default (the `ScreenView`'s `layoutBounds`). It worked well to add linear functions that can alter the scaling on a sliding scale (no pun intended), at that max height (when the ratio halves no longer reach to the top of the screen), the scaling is 1.5. I also had to implement a similar pattern to support repositioning the layer after scaling altered it. I didn't end up doing this for the reset or lock ratio button because I wasn't sure if it was needed, and it would add more complexity because it can't be in the same layer as the controls above. 

Before: 
![image](https://user-images.githubusercontent.com/6856943/91918578-cb074e00-ec6f-11ea-8d7a-f02d4b25e06e.png)

After:
![image](https://user-images.githubusercontent.com/6856943/91918590-d3f81f80-ec6f-11ea-9f0d-eb3b3429711c.png)


@emily-phet please review. Do you recommend adding this same behavior to the reset all button/lock ratio checkbox?

You can test on master or on https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.60/phet/

**Comment by emily-phet** [comment]
@zepumph This looks great! Please apply  to the lock ratio checkbox and reset all as well.

**Comment by zepumph** [comment]
Done now for the bottom controls. Anything else here @emily-phet?
