### ISSUE TITLE
zoom feature breaks AccordionBox titlebar expand/collapse

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#88]
In perhaps the most obscure bug I have ever discovered, it appears that turning on the zoom/mag feature breaks the ability to have an AccordionBox's title bar clickable to toggle expand collapse. It does not effect the behavior of the expand collapse button. 

To reproduce the problem:
* On master in RaP, note that even though AccordionBox's option `titleBarExpandCollapse` is set to true, that feature doesn't work. 
* Turn off zoom mag (through package.json), `grunt update`, and discover that the accordion box's title now toggles expand/collapse.

Assigning to the zoom/mag whiz. Let me know if I can be of assistance.

**Comment by jessegreenberg** [comment]
Interesting, I am seeing this too. I really don't know what is happening yet. But I do see that when zoom is enabled the `collapsedTitleBar` is not in the eventTrail which is why it is not receiving the down event to open:
![image](https://user-images.githubusercontent.com/6396244/87465450-a9c8a080-c5e2-11ea-9d9f-2894c9a0eb6d.png)

**Comment by jessegreenberg** [comment]
This was fixed in https://github.com/phetsims/scenery/issues/1056, and the title of the accordion box is now clickable with or without the zoom feature.
